// Generated by branding/sync.mjs.
pub const PRODUCT: &str = "speech workspace";
pub const ORGANIZATION: &str = "Spanvision Infra";
pub const THEME: &str = "spanvision-mono";
pub const CONFIG_DIRECTORY: &str = "spanvision-speech-workspace";
