import fs from 'node:fs';
import path from 'node:path';
import { spawn, spawnSync } from 'node:child_process';
import { root, brand, digest, fingerprint } from './common.mjs';

export function syncBim({module,emit}) {
  const identity={organization:brand.organization,product:module.productName,mark:module.mark,theme:brand.theme,palette:brand.palette};
  const json=JSON.stringify(identity,null,2)+'\n';
  emit(`${module.directory}/brand.json`,json);
  emit(`${module.directory}/viewer/brand.json`,json);
  const p=brand.palette;
  emit(`${module.directory}/viewer/src/styles/suite-palette.css`,`/* Generated by branding/sync.mjs. */
:root, [data-theme="${brand.theme}"] {
  --theme-page-bg: ${p.page};
  --theme-bg: ${p.surface};
  --theme-bg-lighter: ${p.surface};
  --theme-docbar-bg: ${p.page};
  --theme-surface: ${p.raised};
  --theme-input-bg: ${p.canvas};
  --theme-content-bg: ${p.canvas};
  --theme-text: ${p.textSoft};
  --theme-text-secondary: ${p.muted};
  --theme-text-muted: ${p.muted};
  --theme-border: ${p.border};
  --theme-focus-color: ${p.focus};
}
`);
  emit('suite-hub/public/bim-notices.md',fs.readFileSync(path.join(root,module.directory,'THIRD_PARTY_NOTICES.md'),'utf8'));
}

export function bimPythonPath(module=brand.modules.find(item=>item.id==='bim')) {
  if(process.env.SPANVISION_BIM_PYTHON)return process.env.SPANVISION_BIM_PYTHON;
  const relative=process.platform==='win32'?'.venv/Scripts/python.exe':'.venv/bin/python';
  const local=path.join(root,module.directory,relative);
  return fs.existsSync(local)?local:'python';
}

export function stopBim(child) {
  if(!child||child.exitCode!==null)return;
  if(process.platform==='win32')spawnSync(path.join(process.env.SystemRoot||'C:/Windows','System32/taskkill.exe'),['/PID',String(child.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'});
  else child.kill();
}

export async function startBim(module) {
  const base=path.join(root,module.directory);
  const stamp=JSON.parse(fs.readFileSync(path.join(base,module.dist,'suite-build.json'),'utf8'));
  if(stamp.brandDigest!==digest(module)||stamp.sourceFingerprint!==fingerprint(module))throw new Error('Rebuild BIM Validator to preview the latest edition.');
  const url=`http://127.0.0.1:${module.port}`;
  const matches=active=>active.id===module.id&&active.available&&active.sourceFingerprint===stamp.sourceFingerprint&&active.brandDigest===stamp.brandDigest;
  try {
    const response=await fetch(url+'/__bim/status',{signal:AbortSignal.timeout(1500)});
    let active;
    try {active=await response.json();}catch {throw new Error('BIM preview port is occupied by a different server.');}
    if(!response.ok||!matches(active))throw new Error('BIM preview port is occupied by a different or outdated server.');
    return null;
  } catch(error) {if(error.message.includes('occupied'))throw error;}
  if(!fs.existsSync(bimPythonPath(module))&&!process.env.SPANVISION_BIM_PYTHON)throw new Error('Install the BIM backend dependencies in vision-bim-validator/.venv before previewing.');
  const child=spawn(bimPythonPath(module),['-m','uvicorn','server.suite_preview:app','--host','127.0.0.1','--port',String(module.port),'--no-access-log'],{
    cwd:base,windowsHide:true,stdio:['ignore','pipe','pipe'],
    env:{...process.env,PYTHONPATH:[path.join(base,'src'),process.env.PYTHONPATH].filter(Boolean).join(path.delimiter),CORS_ORIGINS:[`http://127.0.0.1:${brand.hub.port}`,`http://localhost:${brand.hub.port}`,url].join(','),SPANVISION_BIM_STAMP:JSON.stringify({...module,...stamp})}
  });
  child.stdout.on('data',data=>process.stdout.write(data));
  child.stderr.on('data',data=>process.stderr.write(data));
  let failure;child.on('error',error=>failure=error);
  try {
    for(let attempt=0;attempt<100;attempt++) {
      if(failure)throw failure;
      if(child.exitCode!==null)throw new Error('BIM backend failed to start. Check its Python dependencies and preview port.');
      try {const response=await fetch(url+'/__bim/status',{signal:AbortSignal.timeout(800)});if(response.ok&&matches(await response.json()))return child;}catch {}
      await new Promise(resolve=>setTimeout(resolve,200));
    }
    throw new Error('BIM backend did not become ready.');
  } catch(error) {stopBim(child);throw error;}
}
