import fs from 'node:fs';
import path from 'node:path';

export function syncField({root,brand,module,emit}) {
  const app=module.directory;
  const identity={organization:brand.organization,product:module.productName,mark:module.mark,version:'0.3.6',theme:brand.theme,services:{accountsEnabled:false,updaterEnabled:false},palette:brand.palette};
  const json=value=>JSON.stringify(value,null,2)+'\n';
  emit(`${app}/brand.json`,json(identity));
  emit(`${app}/src/brand.json`,json(identity));
  emit(`${app}/src-tauri/src/brand.rs`,`// Generated by branding/sync.mjs.\npub const PRODUCT: &str = ${JSON.stringify(identity.product)};\npub const ORGANIZATION: &str = ${JSON.stringify(identity.organization)};\n`);
  const p=brand.palette;
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-label="FW — Field Workspace"><rect x="1" y="1" width="62" height="62" rx="12" fill="${p.page}" stroke="${p.text}" stroke-opacity=".16"/><g fill="none" stroke="${p.text}" stroke-width="3.5" stroke-linecap="square" stroke-linejoin="miter"><path d="M14 43V22h13M14 32h10"/><path d="m32 22 4 21 7-14 7 14 4-21"/></g></svg>\n`;
  emit(`${app}/public/fw-mark.svg`,svg);
  emit(`${app}/public/favicon.svg`,svg);
  emit('suite-hub/public/fw-mark.svg',svg);
  const tokens=Object.entries(p).map(([key,value])=>`  --sv-${key.replace(/[A-Z]/g,c=>'-'+c.toLowerCase())}: ${value};`).join('\n');
  emit(`${app}/public/brand-palette.css`,`/* Generated by branding/sync.mjs. */\n:root {\n${tokens}\n}\n[data-theme="${identity.theme}"] {\n  color-scheme: dark;\n  --background: var(--sv-page);\n  --surface: var(--sv-surface);\n  --concrete: var(--sv-raised);\n  --deep-forge: var(--sv-page);\n  --night-build: var(--sv-surface);\n  --blueprint-white: var(--sv-text-soft);\n  --text-primary: var(--sv-text);\n  --text-secondary: var(--sv-muted);\n  --text-muted: var(--sv-muted);\n  --scaffold-gray: var(--sv-muted);\n  --construction-amber: var(--sv-text-soft);\n  --construction-amber-hover: var(--sv-text);\n  --signal-orange: var(--sv-text);\n  --warm-gold: var(--sv-text-soft);\n  --primary-color: var(--sv-text-soft);\n  --primary-hover: var(--sv-text);\n  --primary: var(--sv-text-soft);\n  --success: var(--sv-text-soft);\n  --error: var(--sv-text-soft);\n  --danger: var(--sv-text-soft);\n  --info: var(--sv-text-soft);\n  --warning: var(--sv-text-soft);\n  --border-color: var(--sv-border);\n}\n`);
  const config=JSON.parse(fs.readFileSync(path.join(root,app,'src-tauri/tauri.conf.json'),'utf8'));
  Object.assign(config,{productName:identity.product,version:identity.version,identifier:'com.spanvisioninfra.fieldworkspace',mainBinaryName:'spanvision-field-workspace'});
  Object.assign(config.bundle,{publisher:identity.organization,shortDescription:'Construction inspection, handover and quality assurance',targets:['nsis'],resources:{'../legal/':'legal/'}});
  config.app.windows[0].title=`${identity.product} — ${identity.organization}`;
  config.app.windows[0].create=false;
  config.build.devUrl='http://127.0.0.1:4245';
  emit(`${app}/src-tauri/tauri.conf.json`,json(config));
  const pkg=JSON.parse(fs.readFileSync(path.join(root,app,'package.json'),'utf8'));
  Object.assign(pkg,{name:'@spanvision-infra/field-workspace',description:`${identity.product} by ${identity.organization}`,author:identity.organization,license:'CC-BY-SA-4.0'});
  emit(`${app}/package.json`,json(pkg));
}
