import pathlib,re,json
root=pathlib.Path(__file__).resolve().parent.parent
app=root/'spanvision-pile-plane-workspace/apps/pile-plan-studio'
def edit(rel,fn):
    p=app/rel;s=p.read_text(encoding='utf-8');p.write_text(fn(s),encoding='utf-8')
edit('src/components/template/backstage/Backstage.tsx',lambda s:s.replace('import ', 'import ',1).replace('function AboutPanel() {','function AboutPanel() {').replace('  const openExternal = (url: string) => async (e: React.MouseEvent) => {','  const openExternal = (url: string) => async (e: React.MouseEvent) => {'))
edit('src/components/template/backstage/Backstage.tsx',lambda s:'import OpenSourceNotices from "../OpenSourceNotices.tsx";\n'+re.sub(r'  const openExternal = \(url: string\) => async \(e: React.MouseEvent\) => \{[\s\S]*?\n  };\n','',s,count=1).replace('<a className="bs-about-link" href="/legal/UPSTREAM-NOTICES.md" target="_blank" rel="noopener noreferrer">{t("aboutPanel.notices")}</a>','<OpenSourceNotices />'))
edit('src/components/template/settings/SettingsDialog.tsx',lambda s:'import OpenSourceNotices from "../OpenSourceNotices.tsx";\n'+s.replace('<p><strong>{t("about.license")}:</strong> {PRODUCT_INFO.license}</p>','<p><strong>{t("about.license")}:</strong> {PRODUCT_INFO.license}</p><OpenSourceNotices />'))
edit('src/components/template/feedback/FeedbackDialog.tsx',lambda s:re.sub(r'  // ── Copy images to clipboard[\s\S]*?  const handleSubmit','  const handleSubmit',s,count=1))
edit('src/domain/settings/userSettings.test.ts',lambda s:s.replace('theme: "light",\n        interfaceScalePercent','theme: "spanvision-mono",\n        canvasBackground: "auto",\n        interfaceScalePercent',1))
edit('src-primary-entry.test.ts',lambda s:s.replace('/"beforeBuildCommand": "npm run build"/','/"beforeBuildCommand": "node \\.\\.\\/\\.\\.\\/tools\\/build-browser\\.mjs"/').replace('name: "IFCPP project"','name: "Pile Plane Workspace project"').replace('description: "Open Pile Plan Studio IFCPP project"','description: "Pile Plane Workspace IFCPP project"'))
edit('src/integration/ViewerTheme.test.ts',lambda s:s.replace('around the white drawing canvas','around the separately configured drawing canvas').replace(r'background:\s*#f8fafb',r'background:\s*var\(--viewer-background, #f8fafb\)'))
edit('src/productInfo.test.ts',lambda s:s.replace(r'/name:\s*"Open Pile Plan Studio"/',r'/name:\s*brand\.product/').replace(r'/organization:\s*"OpenAEC Foundation"/',r'/organization:\s*brand\.organization/').replace('packageJson.name, "pile-plan-studio"','packageJson.name, "@spanvision-infra/pile-plane-workspace"').replace('"com.openaec.pile-plan-studio"','"com.spanvisioninfra.pileplaneworkspace"').replace('tauriConfig.productName, "Open Pile Plan Studio"','tauriConfig.productName, "Pile Plane Workspace"').replace('tauriConfig.app?.windows?.[0]?.title, "Open Pile Plan Studio"','tauriConfig.app?.windows?.[0]?.title, "Pile Plane Workspace — Spanvision infra"'))
edit('src/components/template/feedback/FeedbackDialog.test.ts',lambda s:s.replace('opens issues in the Pile Plan Studio repository','downloads feedback without opening an upstream issue').replace('assert.match(source, /const GITHUB_OWNER = "OpenAEC-Foundation"/);','assert.match(source, /Pile-Plane-Workspace-feedback\\.md/);').replace('assert.match(source, /const GITHUB_REPO = "pile-plan-studio"/);','assert.doesNotMatch(source, /github\\.com|GITHUB_OWNER|openExternal/);'))
print('Notices integrated and affected product contracts updated.')
