import fs from 'node:fs';
import path from 'node:path';

export function syncGeotechniek({root,brand,module,emit,svg}) {
  const app=`${module.directory}/${module.frontendDirectory}`;
  const palette=brand.palette;
  const identity={organization:brand.organization,product:`${brand.suiteName} · ${module.label}`,suiteName:brand.suiteName,mark:brand.mark,theme:brand.theme,version:'0.4.1',tenant:'spanvision_infra',services:brand.services,palette};
  emit(`${app}/brand.json`,JSON.stringify(identity,null,2)+'\n');
  emit(`${module.directory}/vendor/crates-warehouse/brand.json`,JSON.stringify(identity,null,2)+'\n');
  emit(`${app}/src/brand-palette.css`,monoPalette(fs.readFileSync(path.join(root,app,'src/themes.css'),'utf8'),palette,brand.theme));
  emit(`${app}/public/gw-mark.svg`,svg);
  const config=JSON.parse(fs.readFileSync(path.join(root,app,'src-tauri/tauri.conf.json'),'utf8'));
  config.productName=identity.product;
  config.identifier='com.spanvisioninfra.geotechniek';
  config.mainBinaryName='spanvision-geotechniek-workspace';
  config.bundle.publisher=brand.organization;
  // Directory mappings preserve tenant hierarchy; map globs flatten it.
  config.bundle.resources={'tenants/':'tenants/','icons/file-associations/':'icons/file-associations/','vendor/WebView2Loader.dll':'WebView2Loader.dll'};
  for(const window of config.app.windows)window.title=`${identity.product} — ${identity.organization}`;
  for(const association of config.bundle.fileAssociations||[])if(association.ext.includes('ifcgeo'))association.description=`${identity.product} project / CPT file`;
  emit(`${app}/src-tauri/tauri.conf.json`,JSON.stringify(config,null,2)+'\n');
  const pkg=JSON.parse(fs.readFileSync(path.join(root,app,'package.json'),'utf8'));
  pkg.name='@spanvision-infra/geotechniek-workspace';pkg.description=`${identity.product} by ${brand.organization}`;
  emit(`${app}/package.json`,JSON.stringify(pkg,null,2)+'\n');
  for(const language of ['en','nl']) {
    const base=`${app}/src/i18n/locales/${language}`;
    const common=JSON.parse(fs.readFileSync(path.join(root,base,'common.json'),'utf8'));
    common.appName=identity.product;common.version=`${identity.product} v${identity.version}`;
    emit(`${base}/common.json`,JSON.stringify(common,null,2)+'\n');
    const settings=JSON.parse(fs.readFileSync(path.join(root,base,'settings.json'),'utf8'));
    settings.appearance.mono='Spanvision Mono';settings.appearance.dark=language==='nl'?'Nacht (donker)':'Night (dark)';
    settings.about.appName=identity.product;settings.about.openaecLink=brand.organization;
    settings.about.description=language==='nl'?'Geotechnische werkruimte voor sonderingen, boringen, tekeningen en rapporten.':'Geotechnical workspace for CPT data, boreholes, site drawings and reports.';
    settings.about.builtOn=language==='nl'?'Spanvision werkruimte':'Spanvision workspace';
    emit(`${base}/settings.json`,JSON.stringify(settings,null,2)+'\n');
    const backstage=JSON.parse(fs.readFileSync(path.join(root,base,'backstage.json'),'utf8'));
    Object.assign(backstage.aboutPanel,{appName:identity.product,companyName:brand.organization,description:settings.about.description,companyDescription:language==='nl'?'Een gezamenlijke werkruimte voor infrastructuur en engineering.':'A shared workspace for infrastructure and engineering.',stichting:brand.organization,tagline:'Ground conditions. Clear decisions.',copyright:`${brand.organization} workspace edition · Open-source notices available below.`});
    emit(`${base}/backstage.json`,JSON.stringify(backstage,null,2)+'\n');
  }
  const reportPalette={primary:'#202020',secondary:'#121212',accent:'#555555',warm_gold:'#777777',scaffold_gray:'#999999',background_light:'#FFFFFF',background_card:'#EEEEEE',background_dark:'#121212',text_dark:'#121212',text_light:'#FFFFFF',text:'#121212',text_muted:'#666666',success:'#555555',error:'#202020',info:'#555555'};
  const yaml=`# Generated by branding/sync.mjs.\nbrand:\n  name: ${JSON.stringify(brand.organization)}\n  short_name: ${JSON.stringify(brand.mark)}\n  slug: spanvision_infra\n  tenant: spanvision_infra\n  tagline: ${JSON.stringify(brand.suiteName)}\n  secondary_tagline: "Ground conditions. Clear decisions."\n\ncolors:\n${Object.entries(reportPalette).map(([key,value])=>`  ${key}: "${value}"`).join('\n')}\n\nfonts:\n  heading: SpaceGrotesk-Bold\n  subheading: SpaceGrotesk-Medium\n  body: Inter-Regular\n  body_medium: Inter-Medium\n  body_bold: Inter-SemiBold\n  mono: JetBrainsMono-Regular\n\nfont_files:\n  SpaceGrotesk-Bold: fonts/SpaceGrotesk-Bold.ttf\n  SpaceGrotesk-Medium: fonts/SpaceGrotesk-Medium.ttf\n  Inter-Regular: fonts/Inter-Regular.ttf\n  Inter-Medium: fonts/Inter-Medium.ttf\n  Inter-SemiBold: fonts/Inter-SemiBold.ttf\n  JetBrainsMono-Regular: fonts/JetBrainsMono-Regular.ttf\n\nmargins:\n  top_mm: 20\n  bottom_mm: 20\n  left_mm: 20\n  right_mm: 20\n\ngradient:\n  accent_strip: ["#202020", "#777777", "#999999"]\n`;
  const reportExtras = '\nlogos:\n  main: logos/gw-wordmark.png\n  white: logos/gw-wordmark.png\ncontact:\n  name: '+JSON.stringify(brand.organization)+'\n  address: '+JSON.stringify(brand.suiteName)+'\nfooter:\n  height: 12\n  elements:\n    - type: text\n      x: 20\n      y: 12\n      content: '+JSON.stringify(brand.organization+' · '+brand.suiteName)+'\n      font: $body\n      size: 8\n      color: "#666666"\n    - type: text\n      x: 190\n      y: 12\n      content: "{page} / {total_pages}"\n      align: right\n      font: $body\n      size: 8\n      color: "#666666"\nstyles:\n  Heading1:\n    fontName: SpaceGrotesk-Bold\n    textColor: "#121212"\n  Normal:\n    fontName: Inter-Regular\n    textColor: "#121212"\npages:\n  cover:\n    logo_x_ref: 55\n    logo_y_ref: 770\n    logo_w_ref: 225\n  backcover:\n    logo_key: white\n    logo_x_ref: 160\n    logo_y_ref: 445\n    logo_w_ref: 275\n    contact_x_ref: 160\n    contact_y_ref: 335\n';
  emit(`${app}/src-tauri/tenants/spanvision_infra/brand.yaml`,yaml+reportExtras);
  emit(`${app}/src-tauri/tenants/openaec_foundation/brand.yaml`,yaml+reportExtras);
}

function monoPalette(source,p,theme) {
  const names=[...new Set([...source.matchAll(/(--theme-[\w-]+)\s*:/g)].map(match=>match[1]).concat(['--theme-bg-hover','--theme-border-strong','--theme-bg-elevated','--theme-bg-muted','--theme-error-bg','--theme-error-fg','--theme-error-border','--theme-warning-bg','--theme-warning-fg','--theme-warning-border','--theme-bg-active','--theme-input-bg']))];
  const white=p.text,soft=p.textSoft,muted=p.muted,border=p.border,page=p.page,surface=p.surface,raised=p.raised;
  const special={
    'bg-hover':'#333333','bg-elevated':p.canvas,'bg-muted':surface,'error-bg':raised,'error-fg':soft,'error-border':p.focus,'warning-bg':raised,'warning-fg':soft,'warning-border':p.focus,'bg-active':'#333333','input-bg':raised,
    'bg':page,'bg-lighter':surface,'docbar-bg':surface,'surface':surface,'content-bg':p.canvas,
    'accent':soft,'accent-hover':white,'accent-text':page,'accent-soft':'rgba(255,255,255,.06)','accent-tint':'rgba(255,255,255,.85)',
    'hover':'rgba(255,255,255,.08)','hover-strong':'rgba(255,255,255,.14)','active':soft,'focus-color':p.focus,
    'danger-color':soft,'danger-hover':white,'file-tab-bg':raised,'file-tab-hover':'#333333','file-tab-text':white,
    'status-bg':page,'status-border':border,'status-text':soft,'status-text-label':muted,'status-hover':'rgba(255,255,255,.08)','status-separator':border,
    'dialog-overlay':'rgba(0,0,0,.72)','dialog-bg':surface,'dialog-header-bg':raised,'dialog-sidebar-bg':surface,'dialog-content-bg':surface,
    'dialog-input-bg':raised,'dialog-input-text':soft,'dialog-btn-bg':soft,'dialog-btn-text':page,'dialog-btn-hover':white,
    'btn-primary-bg':soft,'btn-primary-text':page,'btn-primary-border':soft,'btn-primary-hover-bg':white,'btn-primary-hover-text':page,
    'btn-secondary-bg':raised,'btn-secondary-text':soft,'btn-secondary-hover-bg':'#333333','btn-secondary-hover-border':p.focus,
    'ribbon-group-label':muted,'placeholder-icon':muted,'placeholder-heading':soft,'placeholder-text':muted
  };
  const value = name => {
    const key=name.replace('--theme-','');
    if(special[key])return special[key];
    if(/shadow/.test(key))return '0 12px 40px rgba(0,0,0,.5)';
    if(/border|separator/.test(key))return border;
    if(/secondary|muted|faint|shortcut|label/.test(key))return muted;
    if(/text|icon/.test(key))return soft;
    if(/active-bg/.test(key))return 'rgba(255,255,255,.16)';
    if(/hover/.test(key))return 'rgba(255,255,255,.10)';
    return soft;
  };
  return `/* Generated from branding/brand.json. Domain colors remain in themes.css. */\n[data-theme="${theme}"] {\n  color-scheme: dark;\n${names.map(name=>`  ${name}: ${value(name)};`).join('\n')}\n  --theme-canvas: ${p.canvas};\n}\n`;
}
