import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';
import pngToIco from 'png-to-ico';

export function syncPile({root,brand,module,emit}) {
  const app=`${module.directory}/${module.frontendDirectory}`;
  const identity={organization:brand.organization,product:module.productName,mark:module.mark,version:'0.4.2',theme:brand.theme,palette:brand.palette};
  emit(`${module.directory}/brand.json`,JSON.stringify(identity,null,2)+'\n');
  emit(`${app}/src/brand.json`,JSON.stringify(identity,null,2)+'\n');
  emit(`${module.directory}/crates/pile-plan-core/src/brand.rs`,`// Generated by branding/sync.mjs.\npub(crate) const APPLICATION_NAME: &str = ${JSON.stringify(identity.product)};\n`);
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-label="PPW — Pile Plane Workspace"><rect x="1" y="1" width="62" height="62" rx="12" fill="${brand.palette.page}" stroke="${brand.palette.text}" stroke-opacity=".16"/><g fill="none" stroke="${brand.palette.text}" stroke-width="2.7" stroke-linejoin="miter"><path d="M10 44V22h10v11H10M25 44V22h10v11H25M39 22l4 22 6-13 6 13 4-22"/></g></svg>\n`;
  for(const file of ['public/ppw-mark.svg','public/pile-plan-studio-icon.svg'])emit(`${app}/${file}`,svg);
  emit('suite-hub/public/ppw-mark.svg',svg);
  const theme=fs.readFileSync(path.join(root,app,'src/themes.css'),'utf8');
  const tokens=[...new Set([...theme.matchAll(/(--theme-[\w-]+)\s*:/g)].map(m=>m[1]))];
  const value=name=>{
    if(/shadow/.test(name))return '0 8px 30px rgba(0,0,0,.45)';
    if(/overlay/.test(name))return 'rgba(0,0,0,.65)';
    if(/focus/.test(name))return 'var(--sv-focus)';
    if(/border|separator/.test(name))return 'var(--sv-border)';
    if(/accent-text|primary-text|primary-hover-text/.test(name))return 'var(--sv-page)';
    if(/muted|faint|secondary|shortcut|group-label|tab-text|text-label/.test(name))return 'var(--sv-muted)';
    if(/text|icon|danger-color|danger-hover|accent$|accent-hover/.test(name))return 'var(--sv-text-soft)';
    if(/primary.*bg/.test(name))return 'var(--sv-text-soft)';
    if(/hover|active|accent-soft|accent-tint|input-bg|btn-bg/.test(name))return 'var(--sv-raised)';
    if(/content-bg/.test(name))return 'var(--sv-canvas)';
    if(/bg-lighter|surface|dialog|ribbon|file-tab/.test(name))return 'var(--sv-surface)';
    return 'var(--sv-page)';
  };
  const css=`/* Generated by branding/sync.mjs. */\n:root {\n${Object.entries(brand.palette).map(([k,v])=>`  --sv-${k.replace(/[A-Z]/g,c=>'-'+c.toLowerCase())}: ${v};`).join('\n')}\n}\n[data-theme="${brand.theme}"] {\n  color-scheme: dark;\n${tokens.map(k=>`  ${k}: ${value(k)};`).join('\n')}\n  --theme-warning-bg: var(--sv-raised);\n}\n[data-theme="${brand.theme}"] :focus-visible { outline:2px solid var(--sv-focus); outline-offset:2px; }\n[data-theme="${brand.theme}"] input { accent-color:var(--sv-text-soft); }\n`;
  emit(`${app}/src/styles/brand-palette.css`,css);
  const config=JSON.parse(fs.readFileSync(path.join(root,app,'src-tauri/tauri.conf.json'),'utf8'));
  Object.assign(config,{productName:identity.product,identifier:'com.spanvisioninfra.pileplaneworkspace',mainBinaryName:'spanvision-pile-plane-workspace'});
  config.bundle.publisher=identity.organization;
  config.bundle.shortDescription=`${identity.product} by ${identity.organization}`;
  config.bundle.resources=['../../../legal/'];
  config.bundle.targets=['nsis'];
  config.build.beforeBuildCommand='node ../../tools/build-browser.mjs';
  for(const window of config.app.windows)window.title=`${identity.product} — ${identity.organization}`;
  for(const association of config.bundle.fileAssociations||[])Object.assign(association,{name:`${identity.product} project`,description:`${identity.product} IFCPP project`});
  emit(`${app}/src-tauri/tauri.conf.json`,JSON.stringify(config,null,2)+'\n');
  fs.cpSync(path.join(root,module.directory,'legal'),path.join(root,app,'public/legal'),{recursive:true});
}

export async function generatePileIcons(root,module) {
  const app=path.join(root,module.directory,module.frontendDirectory);
  const master=await sharp(fs.readFileSync(path.join(app,'public/ppw-mark.svg'))).resize(1024).png().toBuffer();
  const dir=path.join(app,'src-tauri/icons');fs.mkdirSync(dir,{recursive:true});
  for(const size of [32,128,256])await sharp(master).resize(size).png().toFile(path.join(dir,`${size}x${size}.png`));
  await sharp(master).png().toFile(path.join(dir,'icon.png'));
  const ico=await pngToIco(await sharp(master).resize(256).png().toBuffer());
  fs.writeFileSync(path.join(dir,'icon.ico'),ico);fs.writeFileSync(path.join(app,'public/favicon.ico'),ico);
}
