import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import sharp from 'sharp';
import pngToIco from 'png-to-ico';

export function syncPointcloud({root,brand,module,emit}) {
  const app=module.directory;
  const identity={organization:brand.organization,product:module.productName,mark:module.mark,version:'0.3.0',theme:brand.theme,palette:brand.palette};
  const json=value=>JSON.stringify(value,null,2)+'\n';
  emit(`${app}/brand.json`,json(identity));
  emit(`${app}/src/brand.json`,json(identity));
  emit(`${app}/src-tauri/src/brand.rs`,`// Generated by branding/sync.mjs.\npub const PRODUCT: &str = ${JSON.stringify(identity.product)};\npub const ORGANIZATION: &str = ${JSON.stringify(identity.organization)};\n`);
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-label="PW — Pointcloud Workspace"><rect x="1" y="1" width="62" height="62" rx="12" fill="${brand.palette.page}" stroke="${brand.palette.text}" stroke-opacity=".16"/><g fill="none" stroke="${brand.palette.text}" stroke-width="3.5" stroke-linecap="square" stroke-linejoin="miter"><path d="M13 43V22h13v11H13"/><path d="m33 22 4 21 7-14 7 14 4-21"/></g></svg>\n`;
  for(const file of ['public/logo.svg','public/pw-mark.svg'])emit(`${app}/${file}`,svg);
  emit('suite-hub/public/pw-mark.svg',svg);
  const p=brand.palette;
  const tokens=Object.entries(p).map(([key,value])=>`  --sv-${key.replace(/[A-Z]/g,c=>'-'+c.toLowerCase())}: ${value};`).join('\n');
  const css=`/* Generated by branding/sync.mjs. Edit branding/brand.json. */\n:root {\n${tokens}\n}\n[data-theme="${brand.theme}"] {\n  color-scheme: dark;\n  --theme-bg: var(--sv-page);\n  --theme-surface: var(--sv-surface);\n  --theme-surface-elevated: var(--sv-raised);\n  --theme-border: var(--sv-border);\n  --theme-border-light: var(--sv-border);\n  --theme-accent: var(--sv-text-soft);\n  --theme-accent-hover: var(--sv-text);\n  --theme-text: var(--sv-text-soft);\n  --theme-text-dim: var(--sv-muted);\n  --theme-text-muted: var(--sv-muted);\n  --theme-grid: #333333;\n  --theme-grid-major: #444444;\n  --theme-input-bg: var(--sv-raised);\n  --theme-hover: rgba(255,255,255,.08);\n  --theme-active: rgba(255,255,255,.16);\n  --theme-active-border: rgba(255,255,255,.58);\n  --theme-dropdown-bg: var(--sv-surface);\n  --theme-scrollbar-track: var(--sv-page);\n  --theme-scrollbar-thumb: #555555;\n  --theme-ribbon-bg: linear-gradient(to bottom,#202020,#121212);\n  --theme-ribbon-tab-bg: var(--sv-surface);\n  --theme-ribbon-content-bg: var(--sv-surface);\n  --theme-file-tab-bg: var(--sv-raised);\n  --theme-file-tab-hover: #333333;\n  --theme-bg-panel: var(--sv-surface);\n  --theme-bg-deep: var(--sv-page);\n  --theme-canvas: var(--sv-canvas);\n  --theme-primary-bg: var(--sv-text-soft);\n  --theme-primary-text: var(--sv-page);\n  --theme-error: var(--sv-text-soft);\n  --theme-focus: var(--sv-focus);\n}\n`;
  emit(`${app}/src/styles/brand-palette.css`,css);
  const config=JSON.parse(fs.readFileSync(path.join(root,app,'src-tauri/tauri.conf.json'),'utf8'));
  Object.assign(config,{productName:identity.product,identifier:'com.spanvisioninfra.pointcloudworkspace',mainBinaryName:'spanvision-pointcloud-workspace'});
  config.bundle.publisher=identity.organization;
  config.bundle.shortDescription=`${identity.product} by ${identity.organization}`;
  config.build.devUrl='http://localhost:3013';
  for(const window of config.app.windows)window.title=`${identity.product} — ${identity.organization}`;
  emit(`${app}/src-tauri/tauri.conf.json`,json(config));
  const pkg=JSON.parse(fs.readFileSync(path.join(root,app,'package.json'),'utf8'));
  Object.assign(pkg,{name:'@spanvision-infra/pointcloud-workspace',description:`${identity.product} by ${identity.organization}`,author:identity.organization,license:'LGPL-3.0-or-later'});
  Object.assign(pkg.scripts,{typecheck:'tsc --noEmit',preview:'vite preview --host 127.0.0.1 --port 4250 --strictPort'});
  emit(`${app}/package.json`,json(pkg));
  for(const file of ['UPSTREAM-NOTICES.md','DEPENDENCY-NOTICES.md']) {
    const source=path.join(root,app,'legal',file);
    if(fs.existsSync(source))emit(`${app}/public/legal/${file}`,fs.readFileSync(source,'utf8'));
  }
  emit(`${app}/public/legal/LICENSE.md`,fs.readFileSync(path.join(root,app,'LICENSE.md'),'utf8'));
}

export async function generatePointcloudIcons(root,module) {
  const app=path.join(root,module.directory);
  const buffer=await sharp(fs.readFileSync(path.join(app,'public/pw-mark.svg'))).resize(1024).png().toBuffer();
  const master=path.join(app,'src-tauri/icons/master.png');fs.writeFileSync(master,buffer);
  execFileSync(process.execPath,[path.join(app,'node_modules/@tauri-apps/cli/tauri.js'),'icon',master,'--output',path.join(app,'src-tauri/icons')],{stdio:'pipe'});
  fs.writeFileSync(path.join(app,'public/favicon.ico'),await pngToIco(await sharp(buffer).resize(256).png().toBuffer()));
  console.log('PW application and native packaging icons generated.');
}
