import fs from 'node:fs';
import path from 'node:path';

export function syncSpeech({root,brand,module,emit}) {
  const app=module.directory;
  const identity={organization:brand.organization,product:module.productName,mark:module.mark,version:'0.12.0',theme:brand.theme,services:{accountsEnabled:false,remoteTranscriptionEnabled:false},palette:brand.palette};
  const json=value=>JSON.stringify(value,null,2)+'\n';
  emit(`${app}/brand.json`,json(identity));
  emit(`${app}/src/brand.json`,json(identity));
  emit(`${app}/src-tauri/src/brand.rs`,`// Generated by branding/sync.mjs.\npub const PRODUCT: &str = ${JSON.stringify(identity.product)};\npub const ORGANIZATION: &str = ${JSON.stringify(identity.organization)};\npub const THEME: &str = ${JSON.stringify(identity.theme)};\npub const CONFIG_DIRECTORY: &str = "spanvision-speech-workspace";\n`);
  const p=brand.palette;
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-label="${identity.mark} — ${identity.product}"><rect x="1" y="1" width="62" height="62" rx="12" fill="${p.page}" stroke="${p.text}" stroke-opacity=".16"/><g fill="none" stroke="${p.text}" stroke-width="3.5" stroke-linecap="square" stroke-linejoin="miter"><path d="M26 22H15v10h11v11H15"/><path d="m33 22 4 21 7-14 7 14 4-21"/></g></svg>\n`;
  emit(`${app}/public/sw-mark.svg`,svg);emit(`${app}/app-icon.svg`,svg);
  const tokens=Object.entries(p).map(([key,value])=>`  --sv-${key.replace(/[A-Z]/g,c=>'-'+c.toLowerCase())}: ${value};`).join('\n');
  const css=`/* Generated by branding/sync.mjs. */\n:root {\n${tokens}\n}\n:root,[data-theme="${brand.theme}"],[data-theme="dark"] {\n  color-scheme: dark;\n  --theme-sidebar-bg: var(--sv-surface);\n  --theme-sidebar-hover: rgba(255,255,255,.08);\n  --theme-sidebar-active: rgba(255,255,255,.14);\n  --theme-border-light: var(--sv-border);\n  --theme-text: var(--sv-text-soft);\n  --theme-text-dim: var(--sv-muted);\n  --theme-text-muted: var(--sv-muted);\n  --theme-hover: rgba(255,255,255,.08);\n  --theme-active: var(--sv-text);\n  --theme-active-border: var(--sv-text);\n  --theme-input-bg: var(--sv-raised);\n  --theme-accent: var(--sv-text-soft);\n  --theme-accent-hover: var(--sv-text);\n  --theme-bg: var(--sv-canvas);\n  --theme-bg-card: var(--sv-surface);\n  --theme-bg-elevated: var(--sv-raised);\n  --theme-chrome: var(--sv-page);\n  --theme-primary-text: var(--sv-page);\n  --theme-focus: var(--sv-focus);\n  --success: var(--sv-text-soft);\n  --danger: var(--sv-text-soft);\n  --recording: var(--sv-text);\n}\n[data-theme="light"] {\n  color-scheme: light;\n  --theme-sidebar-bg: #EEEEEE;\n  --theme-sidebar-hover: rgba(0,0,0,.06);\n  --theme-sidebar-active: rgba(0,0,0,.12);\n  --theme-border-light: rgba(0,0,0,.2);\n  --theme-text: #121212;\n  --theme-text-dim: #555555;\n  --theme-text-muted: #555555;\n  --theme-hover: rgba(0,0,0,.06);\n  --theme-active: #000000;\n  --theme-active-border: #000000;\n  --theme-input-bg: #FFFFFF;\n  --theme-accent: #121212;\n  --theme-accent-hover: #000000;\n  --theme-bg: #FFFFFF;\n  --theme-bg-card: #EEEEEE;\n  --theme-bg-elevated: #E0E0E0;\n  --theme-chrome: #EEEEEE;\n  --theme-primary-text: #FFFFFF;\n  --theme-focus: rgba(0,0,0,.65);\n  --success: #121212;\n  --danger: #121212;\n  --recording: #000000;\n}\n`;
  emit(`${app}/src/styles/brand-palette.css`,css);
  const config=JSON.parse(fs.readFileSync(path.join(root,app,'src-tauri/tauri.conf.json'),'utf8'));
  Object.assign(config,{productName:identity.product,identifier:'com.spanvisioninfra.speechworkspace',mainBinaryName:'spanvision-speech-workspace'});
  config.bundle.publisher=identity.organization;
  for(const window of config.app.windows) window.title=`${identity.product} — ${identity.organization}`;
  emit(`${app}/src-tauri/tauri.conf.json`,json(config));
  const pkg=JSON.parse(fs.readFileSync(path.join(root,app,'package.json'),'utf8'));
  Object.assign(pkg,{name:'@spanvision-infra/speech-workspace',description:`${identity.product} by ${identity.organization}`,author:identity.organization});
  emit(`${app}/package.json`,json(pkg));
}
