import fs from 'node:fs';
import path from 'node:path';
import { brand, root, displayName, write, files } from './common.mjs';
import { syncGeotechniek } from './geotechniek.mjs';
import { syncSpeech } from './speech.mjs';
import { syncStl } from './stl.mjs';
import { syncField } from './field.mjs';
import { syncPile } from './pile.mjs';
import { syncPointcloud } from './pointcloud.mjs';
import { syncBim } from './bim.mjs';
import { syncStudio } from './studios.mjs';

const checking = process.argv.includes('--check');
const moduleFilter = process.argv.find(arg=>arg.startsWith('--modules='))?.slice('--modules='.length).split(',');
const selectedModules = brand.modules.filter(module=>!moduleFilter||moduleFilter.includes(module.id));
const errors = [];
function emit(file, content) {
  if (checking) {
    if (!fs.existsSync(path.join(root,file)) || fs.readFileSync(path.join(root,file),'utf8') !== content) errors.push(file);
  } else write(file,content);
}
const json = value => JSON.stringify(value,null,2)+'\n';
function updateJson(file, transform) {
  const value = JSON.parse(fs.readFileSync(path.join(root,file),'utf8'));
  transform(value);
  emit(file,json(value));
}
function syncPresentation(module, old) {
  const before=old.productName||old.product;
  const oldOrganization=old.organizationName||old.organization;
  const replacements=[];
  if(before&&before.length>8&&before!==displayName(module))replacements.push([before,displayName(module)]);
  const organization=module.organization||brand.organization;
  if(oldOrganization&&oldOrganization!==organization)replacements.push([oldOrganization,organization]);
  if(organization!=='Spanvision infra')replacements.push(['Spanvision infra',organization]);
  if(!replacements.length)return;
  const dirs=module.id==='cad'?['src','site','locales','packaging','web']:module.id==='ifc'?['apps/desktop/src','apps/desktop/index.html']:module.id==='frame'?['ui/src','ui/index.html']:module.id==='calculation'?['packages/desktop/src','packages/web/src','packages/web/index.html']:module.id==='stl'?['web']:module.frontendDirectory?[`${module.frontendDirectory}/src`,`${module.frontendDirectory}/public`,`${module.frontendDirectory}/index.html`]:['src','js','preview','public','index.html'];
  for(const dir of dirs)for(const file of presentationFiles(path.join(module.directory,dir))) {
    if(!/\.(tsx?|jsx?|json|rs|ftl|html|xml|desktop|plist|wxs)$/.test(file)||/\.test\.|[\\/]test[\\/]/.test(file))continue;
    let content=fs.readFileSync(file,'utf8');for(const [a,b] of replacements)content=content.replaceAll(a,b);
    emit(path.relative(root,file),content);
  }
}
function presentationFiles(relative) {
  const absolute=path.join(root,relative);
  return fs.existsSync(absolute)&&fs.statSync(absolute).isFile()?[absolute]:files(relative);
}
const p = brand.palette;
const css = `/* Generated by branding/sync.mjs. Edit branding/brand.json. */\n:root, .ocs-embed-root {\n${Object.entries(p).map(([k,v])=>`  --sv-${k.replace(/[A-Z]/g,c=>'-'+c.toLowerCase())}: ${v};`).join('\n')}\n}\n[data-theme="${brand.theme}"] {\n  --theme-bg: var(--sv-page);\n  --theme-titlebar-bg: var(--sv-page);\n  --theme-surface: var(--sv-surface);\n  --theme-content-bg: var(--sv-canvas);\n  --theme-canvas: var(--sv-canvas);\n  --theme-text: var(--sv-text-soft);\n  --theme-text-muted: var(--sv-muted);\n  --theme-border: var(--sv-border);\n  --theme-focus-color: var(--sv-focus);\n  --theme-app-menu-item-hover-text: var(--sv-text);\n  --theme-panel-tab-hover-text: var(--sv-text);\n}\n[data-theme="${brand.theme}"] :focus-visible { outline: 2px solid var(--sv-focus); outline-offset: 3px; }\n`;
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-label="${brand.mark} — ${brand.suiteName}"><rect x="1" y="1" width="62" height="62" rx="12" fill="${p.page}" stroke="${p.text}" stroke-opacity=".16"/><g fill="none" stroke="${p.text}" stroke-width="3.5" stroke-linecap="square" stroke-linejoin="miter"><path d="M26 22h-9l-5 5v11l5 5h9V32h-7"/><path d="m32 22 4 21 7-14 7 14 4-21"/></g></svg>\n`;
function modulePalette(module) {
  const file=module.id==='calc'?'calc-workspace/src/styles/themes.css':module.id==='pdf'?'spanvision-pdf-workspace/open-pdf-studio/styles/themes.css':module.id==='cad2d'?'spanvision-2d-cad-workspace/src/styles/web.css':'ifc-view/apps/desktop/src/styles/global.css';
  const source=fs.readFileSync(path.join(root,file),'utf8');
  const start=module.id==='ifc'?0:source.lastIndexOf('/* Spanvision Mono:');
  const block=module.id==='ifc'?source.slice(0,source.indexOf('}')+1):module.id==='cad2d'?source.slice(start,source.indexOf('}',source.indexOf('[data-theme=',start))+1):source.slice(start);
  const original={'#000000':'page','#121212':'surface','#1B1B1B':'canvas','#202020':'raised','#FFFFFF':'text','#EEEEEE':'text-soft','#999999':'muted'};
  const tokens=[];
  for(const match of block.matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)) {
    let value=match[2].trim();let hex=value.toUpperCase();
    if(/^#[0-9A-F]{3}$/.test(hex))hex='#'+hex.slice(1).split('').map(c=>c+c).join('');
    if(original[hex])value=`var(--sv-${original[hex]})`;
    if(/focus/.test(match[1]))value='var(--sv-focus)';
    if(/border$/.test(match[1])&&/^rgba/.test(value))value='var(--sv-border)';
    if(value!==match[2].trim())tokens.push(`  ${match[1]}: ${value};`);
  }
  return css+`\n[data-theme="${brand.theme}"] {\n${tokens.join('\n')}\n}\n`;
}
emit('branding/gw-mark.svg',svg);
emit('branding/palette.css',css);
emit('suite-hub/src/brand.json',json(brand));
emit('suite-hub/public/gw-mark.svg',svg);
const hubOrganization=brand.hub.organization||brand.organization;
const hubSvg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-label="${hubOrganization}"><rect x="1" y="1" width="62" height="62" rx="12" fill="${p.page}" stroke="${p.text}" stroke-opacity=".2"/><g fill="none" stroke="${p.text}" stroke-width="3.5" stroke-linecap="square" stroke-linejoin="miter"><path d="M33 21H19l-5 5v4l5 3h9l5 4v3l-5 4H14"/><path d="M44 21h8m-4 0v23m-4 0h8"/></g></svg>\n`;
emit('suite-hub/public/spanvision-mark.svg',hubSvg);
emit('suite-hub/src/palette.css',css);
emit('suite-hub/public/studio-notices.md','# Studio source notices\n\n'+brand.modules.filter(module=>module.kind==='studio').map(module=>`- [${module.label}](${module.id}-notices.txt)`).join('\n')+'\n\nEach studio retains its supplied source licenses and third-party attribution.\n');
emit('spanvision-pdf-workspace/mcp-stdio/brand.json',json({organization:brand.organization,product:displayName(brand.modules.find(m=>m.id==='pdf')),mark:brand.mark}));

for (const module of selectedModules) {
  // Source snapshots can contain display names as well as generated identity files.
  const identityPath=module.id==='ifc'?'ifc-view/brands/spanvision/brand.json':module.id==='pdf'?'spanvision-pdf-workspace/brand.json':`${module.directory}/brand.json`;
  if(fs.existsSync(path.join(root,identityPath)))syncPresentation(module,JSON.parse(fs.readFileSync(path.join(root,identityPath),'utf8')));
  if(module.kind==='studio') {syncStudio({root,brand,module,emit});continue;}
  if(module.id==='bim') {syncBim({module,emit});continue;}
  if(module.id==='pile') {syncPile({root,brand,module,emit});continue;}
  if(module.id==='pointcloud') { syncPointcloud({root,brand,module,emit}); continue; }
  if(module.id==='field') { syncField({root,brand,module,emit}); continue; }
  if(module.id==='stl') { syncStl({module,emit}); continue; }
  const name = displayName(module);
  const organization = module.organization || brand.organization;
  const mark = module.mark || brand.mark;
  const logo = module.logo ? fs.readFileSync(path.join(root,module.logo),'utf8') : svg;
  if(module.id==='speech') { syncSpeech({root,brand,module,emit}); continue; }
  if(module.id==='geo') { syncGeotechniek({root,brand,module,emit,svg}); continue; }
  if (module.id === 'cad') {
    syncPresentation(module,JSON.parse(fs.readFileSync(path.join(root,'SpanvisionCAD/brand.json'),'utf8')));
    updateJson('SpanvisionCAD/brand.json', b=>Object.assign(b,{organization, product:name, display_name:`${name} — ${organization}`, mark, theme:brand.theme}));
    const nativeDisplay=`${name} — ${organization}`;
    for(const file of ['packaging/Info.plist','packaging/SpanvisionCAD.desktop','packaging/com.spanvisioninfra.cad.metainfo.xml','packaging/build_macos_signed.sh','snap/snapcraft.yaml']) {
      const relative=`SpanvisionCAD/${file}`;
      const content=fs.readFileSync(path.join(root,relative),'utf8');
      emit(relative,content.includes(nativeDisplay)?content:content.replaceAll(name,nativeDisplay));
    }
    emit('SpanvisionCAD/assets/logo.svg',logo);
    emit('SpanvisionCAD/site/favicon.svg',logo);
    const color = value => {
      const hex = value.slice(1); const values = [0,2,4].map(i=>parseInt(hex.slice(i,i+2),16));
      return `Color { r: ${values[0]}.0 / 255.0, g: ${values[1]}.0 / 255.0, b: ${values[2]}.0 / 255.0, a: 1.0 }`;
    };
    emit('SpanvisionCAD/src/ui/style/brand_palette.rs',`// Generated by branding/sync.mjs.\nuse iced::Color;\n${Object.entries({PAGE:p.page,SURFACE:p.surface,SURFACE_RAISED:p.canvas,SURFACE_HOVER:p.raised,CANVAS:p.canvas,TEXT:p.text,TEXT_SOFT:p.textSoft,TEXT_MUTED:p.muted}).map(([k,v])=>`pub const ${k}: Color = ${color(v)};`).join('\n')}\npub const CANVAS_RGB: [u8;3] = [${p.canvas.slice(1).match(/../g).map(v=>parseInt(v,16)).join(',')}];\npub const BORDER: Color = Color { r: 1.0, g: 1.0, b: 1.0, a: ${Number(p.border.match(/,([.\d]+)\)/)[1])} };\npub const FOCUS: Color = Color { r: 1.0, g: 1.0, b: 1.0, a: ${Number(p.focus.match(/,([.\d]+)\)/)[1])} };\n`);
    continue;
  }
  const configPath = module.id==='ifc' ? 'ifc-view/brands/spanvision/brand.json' : module.id==='pdf' ? 'spanvision-pdf-workspace/brand.json' : `${module.directory}/brand.json`;
  if(module.id==='cad2d' && !fs.existsSync(path.join(root,configPath))) {
    if(checking)throw new Error(`Missing generated adapter: ${configPath}. Run npm run brand:sync.`);
    write(configPath,json({id:'spanvision-2d-cad-workspace',version:'0.35.0',ifcIdentifier:'Spanvision2D',ifcPropertyPrefix:'SpanvisionInfra'}));
  }
  syncPresentation(module,JSON.parse(fs.readFileSync(path.join(root,configPath),'utf8')));
  updateJson(configPath,b=>{
    if(module.id==='ifc') Object.assign(b,{organizationName:brand.organization,productName:name,ownershipLabel:`by ${brand.organization}`,description:`${name} by ${brand.organization}`,windowTitle:`${name} — ${brand.organization}`,mark:brand.mark,theme:brand.theme});
    else Object.assign(b,{organization,product:name,mark,initials:mark,theme:brand.theme});
    if(module.id==='calc') b.accountsEnabled=brand.services.accountsEnabled;
    if(module.id==='pdf') { b.accounts.enabled=brand.services.accountsEnabled; b.updater.enabled=brand.services.updaterEnabled; }
  });
  const appDir = module.id==='ifc' ? 'ifc-view/apps/desktop' : module.directory;
  updateJson(`${appDir}/src-tauri/tauri.conf.json`,b=>{
    b.productName=name;
    if(module.id==='calc') b.mainBinaryName='Calc workspace';
    b.bundle.publisher=organization;
    for(const window of b.app.windows) window.title=`${name} — ${organization}`;
    for(const association of b.bundle.fileAssociations||[]) {
      if(module.id==='calc' && association.ext.includes('ifcCalc')) { association.name=`${name} estimate`; association.description=`${name} estimate file`; }
      if(module.id==='cad2d' && association.ext.includes('o2d')) association.description=`${name} project`;
    }
  });
  updateJson(`${appDir}/package.json`,b=>{b.description=`${name} by ${organization}`; if(b.author)b.author=organization;});
  const localPalette=modulePalette(module);
  emit(`${appDir}/public/brand-palette.css`,localPalette);
  if(module.id!=='pdf') emit(`${appDir}/src/styles/brand-palette.css`,localPalette);
  if(module.id==='cad2d') {
    const local = JSON.parse(fs.readFileSync(path.join(root,configPath),'utf8'));
    Object.assign(local,{organization,product:name,mark,initials:mark,theme:brand.theme});
    emit(`${appDir}/src/config/brand.ts`, `// Generated by branding/sync.mjs.\nexport const BRAND = ${JSON.stringify(local,null,2)} as const;\n`);
  }
  const marks = module.id==='calc' ? ['public/app-icon.svg','src/assets/app-icon.svg'] : module.id==='pdf' ? ['public/icon.svg','src-tauri/icons/icon-new.svg'] : module.id==='ifc' ? ['public/favicon.svg'] : ['public/logo.svg'];
  for(const file of marks) emit(`${appDir}/${file}`,logo);
  if(module.id==='ifc') emit('ifc-view/brands/spanvision/sv-monogram.svg',svg);
}

if (checking) {
  if (errors.length) throw new Error(`Generated branding has drifted:\n${errors.join('\n')}\nRun npm run brand:sync.`);
  console.log('Shared identity, selected adapters, palette and manifests agree.');
} else {
  console.log(`Synchronized geptechniek workspace branding across ${selectedModules.length} module${selectedModules.length===1?'':'s'} and the hub.`);
}
