import { chromium } from 'playwright';
import fs from 'node:fs'; import path from 'node:path';
import assert from 'node:assert/strict';
const output=path.resolve(import.meta.dirname,'../../qa'); fs.mkdirSync(output,{recursive:true});
const base=process.env.SPANVISION_PREVIEW_URL || 'http://127.0.0.1:3084';
const browser=await chromium.launch({channel:'msedge',headless:true});
const results=[], errors=[], requests=[];
try {
  for (const width of [390,768,1440]) {
    const page=await browser.newPage({viewport:{width,height:1000},deviceScaleFactor:1});
    page.on('pageerror',error=>errors.push({width,message:error.message}));
    page.on('request',request=>{if(/openaec|open-aec|open-feedback|kubernetes\.docker/.test(request.url()))requests.push(request.url());});
    for (const screen of ['landing','login','signup','account','suggestions']) {
      await page.goto(`${base}/preview.html#${screen}`); await page.waitForSelector('.preview-header');
      await page.waitForTimeout(300);
      const dimensions=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,theme:document.documentElement.dataset.theme}));
      assert.ok(dimensions.scroll<=width+1,`${screen} overflow at ${width}: ${dimensions.scroll}`);
      assert.equal(dimensions.theme,'spanvision-mono');
      assert.doesNotMatch(await page.locator('body').innerText(),/OpenAEC|Open PDF Studio|open-aec/);
      await page.screenshot({path:path.join(output,`${screen}-${width}.png`)});
      if(screen==='landing')await page.screenshot({path:path.join(output,`landing-${width}-full.png`),fullPage:true});
      results.push({screen,width,overflow:false});
    }
    await page.goto(`${base}/preview.html#landing`);
    await page.getByRole('button',{name:'Explore scan & OCR',exact:true}).click();
    await page.getByRole('dialog').waitFor();
    const dialogBox=await page.getByRole('dialog').boundingBox();
    assert.ok(dialogBox.x>=0 && dialogBox.x+dialogBox.width<=width+1);
    await page.screenshot({path:path.join(output,`scan-${width}.png`)});
    const buttons=page.getByRole('dialog').getByRole('button');
    await buttons.last().focus();await page.keyboard.press('Tab');
    assert.ok(await page.evaluate(()=>!!document.activeElement?.closest('[role="dialog"]')),'focus escaped scan dialog');
    await page.getByRole('button',{name:'Preview OCR',exact:true}).click();
    await page.getByText('Recognizing text…',{exact:false}).waitFor();
    await page.screenshot({path:path.join(output,`scan-processing-${width}.png`)});
    await page.getByText('Preview complete.',{exact:false}).waitFor();
    await page.screenshot({path:path.join(output,`scan-complete-${width}.png`)});
    await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
    assert.equal(await page.evaluate(()=>document.activeElement?.textContent),'Explore scan & OCR');
    await page.goto(`${base}/preview.html#signup`);
    await page.getByRole('button',{name:'Preview account',exact:true}).click();
    await page.getByRole('alert').waitFor();
    await page.getByRole('textbox',{name:'Full name'}).fill('Taylor Reviewer');
    await page.getByRole('textbox',{name:'Email address'}).fill('review@example.test');
    await page.locator('input[name="password"]').fill('preview-only-123');
    await page.getByRole('button',{name:'Preview account',exact:true}).click();
    await page.waitForURL('**#account');
    assert.equal(await page.evaluate(()=>localStorage.getItem('password')),null);
    await page.getByRole('textbox',{name:'Display name'}).fill('Updated Reviewer');
    await page.getByRole('button',{name:'Save preview changes',exact:false}).click();
    await page.getByRole('status').waitFor();
    results.push({screen:'scan-and-account-interactions',width,passed:true});
    await page.close();
  }
  const editor=await browser.newPage({viewport:{width:1440,height:1000}});
  editor.on('pageerror',error=>errors.push({screen:'editor',message:error.message}));
  editor.on('request',request=>{if(/openaec|open-aec|open-feedback/.test(request.url())) requests.push(request.url());});
  await editor.goto(base);await editor.locator('#placeholder').waitFor();
  await editor.screenshot({path:path.join(output,'workspace-empty-1440.png')});
  const chooser=editor.waitForEvent('filechooser');
  await editor.getByRole('button',{name:'Open PDF',exact:true}).click();
  await (await chooser).setFiles(path.resolve(import.meta.dirname,'../public/sample-project.pdf'));
  await editor.waitForFunction(()=>document.querySelector('#pdf-canvas')?.width>100 && getComputedStyle(document.querySelector('#placeholder')).display==='none',{timeout:30000});
  await editor.waitForTimeout(700);
  await editor.locator('#fit-page-ribbon').click();
  await editor.waitForTimeout(450);
  for(const width of [1440,768,390,1440]){
    if(width===1440)await editor.evaluate(()=>window.__qaCanvas=document.querySelector('#pdf-canvas'));
    await editor.setViewportSize({width,height:1000});await editor.waitForTimeout(350);
    assert.ok(await editor.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
    assert.ok(await editor.evaluate(()=>window.__qaCanvas===document.querySelector('#pdf-canvas')),'canvas replaced on resize');
    await editor.keyboard.press('Control+2');
    await editor.waitForTimeout(250);
    await editor.screenshot({path:path.join(output,`workspace-${width}.png`)});
    results.push({screen:'workspace-with-pdf',width,canvasPreserved:true});
    if(width<1024){
      await editor.getByRole('button',{name:'Pages',exact:true}).click();
      assert.ok(await editor.locator('.left-panel').isVisible());
      await editor.screenshot({path:path.join(output,`workspace-pages-${width}.png`)});
      await editor.getByRole('button',{name:'Pages',exact:true}).click();
      assert.ok(!await editor.locator('.left-panel').isVisible());
      await editor.getByRole('button',{name:'Properties',exact:true}).click();
      assert.ok(await editor.locator('.properties-panel-outer').isVisible());
      await editor.getByRole('button',{name:'Properties',exact:true}).click();
    }
  }
  // Use the live tools and pointer events, then save and reopen the result.
  await editor.evaluate(async()=>{
    const loaded=performance.getEntriesByType('resource').find(r=>/\/js\/core\/state\.(ts|js)(\?|$)/.test(r.name));
    window.__qaState=await import(loaded.name);
  });
  const annotations=()=>editor.evaluate(()=> window.__qaState.getActiveDocument().annotations.map(a=>({id:a.id,type:a.type,color:a.color,strokeColor:a.strokeColor})));
  const initial=await annotations();
  await editor.locator('[data-tab="drawing"]').click();
  await editor.locator('#dr-rect').click();
  const paper=await editor.locator('#pdf-canvas').boundingBox();
  await editor.mouse.move(paper.x+paper.width*.32,paper.y+paper.height*.4);
  await editor.mouse.down();
  await editor.mouse.move(paper.x+paper.width*.55,paper.y+paper.height*.6,{steps:10});
  await editor.mouse.up();
  await editor.waitForFunction(n=>window.__qaState.getActiveDocument().annotations.length>n,initial.length);
  assert.equal((await annotations()).at(-1).type,'box');
  await editor.keyboard.press('Control+z');
  await editor.waitForFunction(n=>window.__qaState.getActiveDocument().annotations.length===n,initial.length);
  await editor.keyboard.press('Control+y');
  await editor.waitForFunction(n=>window.__qaState.getActiveDocument().annotations.length===n+1,initial.length);
  await editor.locator('[data-tab="comment"]').click();
  await editor.locator('#tool-measure-distance').click();
  await editor.mouse.click(paper.x+paper.width*.2,paper.y+paper.height*.76);
  await editor.mouse.click(paper.x+paper.width*.7,paper.y+paper.height*.76);
  await editor.mouse.click(paper.x+paper.width*.5,paper.y+paper.height*.8);
  await editor.waitForFunction(n=>window.__qaState.getActiveDocument().annotations.length===n+2,initial.length);
  const beforeSave=await annotations();
  assert.ok(beforeSave.some(a=>a.type==='measureDistance'),'measurement was not created');
  const downloading=editor.waitForEvent('download');
  await editor.keyboard.press('Control+s');
  const saved=await downloading;
  const savedPath=path.join(output,'verified-save-reopen.pdf');
  await saved.saveAs(savedPath);
  const reopen=editor.waitForEvent('filechooser');
  await editor.locator('.quick-access-btn').first().click();
  await (await reopen).setFiles(savedPath);
  await editor.waitForFunction(n=>{const d=window.__qaState.getActiveDocument();return d?.fileName==='verified-save-reopen.pdf' && d.annotations.length===n;},beforeSave.length,{timeout:30000});
  const afterSave=await annotations();
  const colors=list=>list.map(a=>[a.type,a.color?.toLowerCase(),a.strokeColor?.toLowerCase()]);
  assert.deepEqual(colors(afterSave),colors(beforeSave),'annotation types or colors changed on save');
  await editor.locator('[data-tab="home"]').click();
  await editor.locator('#fit-page-ribbon').click();
  await editor.waitForTimeout(450);
  await editor.screenshot({path:path.join(output,'workspace-edited-1440.png')});
  results.push({screen:'annotation-measurement-undo-redo-save-reopen',passed:true,annotations:afterSave.length});
  // Inspect the real assistant at every width, without configuring a service.
  for(const width of [1440,768,390]){
    await editor.setViewportSize({width,height:1000});
    await editor.getByRole('button',{name:'Open Spanvision assistant',exact:true}).click();
    await editor.locator('.chat-floating').waitFor({state:'visible'});
    assert.ok(await editor.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
    await editor.screenshot({path:path.join(output,`workspace-assistant-${width}.png`)});
    await editor.getByRole('button',{name:'Close assistant',exact:true}).click();
    results.push({screen:'live-assistant',width,passed:true});
  }
  // Restore a legacy preference record and confirm the mounted editor uses it.
  const preferencePage=await browser.newPage();
  await preferencePage.goto(base);
  await preferencePage.evaluate(()=>{localStorage.removeItem('spanvision-pdf-workspace.preferences');localStorage.setItem('pdfEditorPreferences',JSON.stringify({theme:'light',canvasBackground:'#654321',rectStrokeColor:'#00aa66'}));});
  await preferencePage.reload();await preferencePage.locator('#placeholder').waitFor();
  await preferencePage.waitForFunction(()=>document.documentElement.dataset.theme==='light');
  assert.equal(await preferencePage.evaluate(()=>getComputedStyle(document.querySelector('#placeholder')).backgroundColor),'rgb(101, 67, 33)');
  const restored=await preferencePage.evaluate(()=>JSON.parse(localStorage.getItem('spanvision-pdf-workspace.preferences')));
  assert.equal(restored.rectStrokeColor,'#00aa66');
  assert.ok(await preferencePage.evaluate(()=>localStorage.getItem('pdfEditorPreferences')));
  await preferencePage.close();
  results.push({screen:'legacy-preferences-and-canvas-restoration',passed:true});
  const touch=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});
  await touch.goto(`${base}/preview.html`);
  await touch.getByRole('button',{name:'Explore scan & OCR',exact:true}).tap();
  await touch.getByRole('button',{name:'Preview OCR',exact:true}).tap();
  await touch.getByText('Recognizing text…',{exact:false}).waitFor();
  await touch.getByRole('button',{name:'Cancel',exact:true}).tap();
  await touch.getByRole('dialog').waitFor({state:'hidden'});
  await touch.goto(base);await touch.locator('#placeholder').waitFor();
  const mobileChooser=touch.waitForEvent('filechooser');
  await touch.getByRole('button',{name:'Open PDF',exact:true}).tap();
  await (await mobileChooser).setFiles(path.resolve(import.meta.dirname,'../public/sample-project.pdf'));
  await touch.waitForFunction(()=>document.querySelector('#pdf-canvas')?.width>100);
  await touch.getByRole('button',{name:'Pages',exact:true}).tap();
  assert.ok(await touch.locator('.left-panel').isVisible());
  await touch.getByRole('button',{name:'Pages',exact:true}).tap();
  await touch.locator('.ribbon-overflow-btn').tap();
  await touch.locator('.ribbon-overflow-flyout').waitFor();
  const flyout=await touch.locator('.ribbon-overflow-flyout').boundingBox();
  assert.ok(flyout.x>=0 && flyout.x+flyout.width<=391 && flyout.y+flyout.height<=844,'compact ribbon actions are outside the viewport');
  assert.ok(await touch.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await touch.screenshot({path:path.join(output,'workspace-touch-controls-390.png')});
  await touch.keyboard.press('Escape');
  await touch.locator('.ribbon-overflow-flyout').waitFor({state:'hidden'});
  assert.ok(await touch.locator('.ribbon-overflow-btn').evaluate(el=>el===document.activeElement));
  await touch.close();
  results.push({screen:'touch-panels-overflow-controls-and-scan-cancellation',width:390,passed:true});
  await editor.close();
  assert.deepEqual(requests,[],'unexpected upstream connections');
  assert.deepEqual(errors,[],'browser errors');
  fs.writeFileSync(path.join(output,'browser-results.json'),JSON.stringify({results,errors,requests},null,2));
  console.log(`${results.length} browser scenarios passed; screenshots in ${output}`);
} catch(error){fs.writeFileSync(path.join(output,'browser-results.json'),JSON.stringify({results,errors,requests,failure:String(error)},null,2));throw error;}finally{await browser.close();}
