import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const out=path.resolve('qa/speech');const shots=path.join(out,'screenshots');fs.mkdirSync(shots,{recursive:true});
const base='http://127.0.0.1:4240/';const results=[],errors=[],requests=[];
const browser=await chromium.launch({channel:'msedge',headless:true});
const record=(scenario,data={})=>results.push({scenario,...data});
try{
 for(const [width,height] of [[320,740],[390,844],[820,1180],[1440,1000]]){
  const page=await browser.newPage({viewport:{width,height}});
  page.on('pageerror',error=>errors.push({width,message:error.message}));
  page.on('request',request=>{if(/impertio|openaec|open-aec|localhost:3333|\/api\//i.test(request.url()))requests.push(request.url());});
  for(const route of ['landing','workspace','transcribe','suggestions','login','signup','account','settings','dictionary','models','meeting','mic-test','tts','about']){
   await page.goto(base+'#'+route,{waitUntil:'domcontentloaded'});await page.locator('main').waitFor();
   await page.waitForTimeout(150);
   assert.doesNotMatch(await page.locator('body').innerText(),/OpenAEC|Open Speech Studio|Impertio|Open Calc|Monty/i);
   const geometry=await page.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth,main:document.querySelector('main').clientWidth,content:document.querySelector('main').scrollWidth}));
   if(geometry.document>width+1||geometry.content>geometry.main+1)errors.push({message:`${route} overflows at ${width}: ${JSON.stringify(geometry)}`});
   if(route==='landing'){
    const colors=await page.evaluate(()=>{const hero=document.querySelector('.speech-landing');const photo=document.querySelector('.speech-photo img');return {background:getComputedStyle(hero).backgroundColor,filter:getComputedStyle(photo).filter};});
    assert.equal(colors.background,'rgb(0, 0, 0)');assert.equal(colors.filter,'none');
   }
   if(route==='workspace'){await page.getByRole('button',{name:'Load sample transcript'}).click();await page.getByRole('textbox',{name:'Edit sample transcript'}).fill('A reviewed sample transcript with clear next steps.');assert.match(await page.getByRole('textbox',{name:'Edit sample transcript'}).inputValue(),/reviewed sample/);}
   await page.screenshot({path:path.join(shots,`${route}-${width}.png`)});record('responsive-screen',{route,width});
  }
  await page.goto(base+'#transcribe');await page.getByRole('button',{name:'Explore audio import'}).click();
  const dialog=page.getByRole('dialog');await dialog.waitFor();let box=await dialog.boundingBox();assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=width+1&&box.y+box.height<=height+1);
  await dialog.getByRole('button',{name:'Preview transcript',exact:true}).focus();await page.keyboard.press('Tab');assert.ok(await page.evaluate(()=>document.activeElement.closest('dialog')));
  await page.screenshot({path:path.join(shots,`audio-dialog-${width}.png`)});
  await dialog.getByRole('button',{name:'Preview transcript',exact:true}).click();await dialog.getByRole('status').waitFor();await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await dialog.waitFor({state:'hidden'});
  assert.match(await page.evaluate(()=>document.activeElement.textContent),/Explore audio import/);
  await page.getByRole('button',{name:'Explore audio import'}).click();await dialog.getByRole('button',{name:'Preview transcript',exact:true}).click();await dialog.getByText('Preview complete.',{exact:false}).waitFor();await dialog.getByRole('button',{name:'Open sample transcript',exact:false}).click();await page.waitForURL('**#workspace');assert.match(await page.getByRole('textbox',{name:'Edit sample transcript'}).inputValue(),/foundation drawings/);record('import-cancel-complete-focus',{width});
  await page.goto(base+'#signup');await page.getByRole('button',{name:'Preview account',exact:true}).click();await page.getByRole('alert').waitFor();assert.match(await page.getByRole('alert').innerText(),/name/);
  await page.getByRole('textbox',{name:'Full name'}).fill('Taylor Reviewer');await page.getByRole('textbox',{name:'Email address'}).fill('review@example.test');await page.locator('input[name=password]').fill('preview-password-123');await page.getByRole('button',{name:'Preview account',exact:true}).click();await page.waitForURL('**#account');assert.equal(await page.getByRole('textbox',{name:'Display name'}).inputValue(),'Taylor Reviewer');await page.getByRole('textbox',{name:'Display name'}).fill('Updated Reviewer');await page.getByRole('button',{name:'Save preview changes',exact:false}).click();await page.getByRole('status').waitFor();
  const storage=await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}));assert.doesNotMatch(storage,/Taylor|Updated|preview-password|review@example/);await page.reload();assert.equal(await page.getByRole('textbox',{name:'Display name'}).inputValue(),'Alex Morgan');record('account-validation-memory-only',{width});
  if(width<600){await page.getByRole('button',{name:'Open navigation'}).click();assert.equal(await page.getByRole('button',{name:'Open navigation'}).getAttribute('aria-expanded'),'true');const last=page.locator('#speech-sidebar button:not(:disabled)').last();await last.focus();await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.className),'mobile-menu');await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'Open navigation'}).getAttribute('aria-expanded'),'false');await page.getByRole('button',{name:'Open navigation'}).click();await page.getByRole('button',{name:'Close navigation'}).click({position:{x:width-8,y:100}});record('mobile-navigation-keyboard-touch',{width});}
  await page.goto(base+'#settings');await page.getByLabel('Appearance').selectOption('light');await page.reload();assert.equal(await page.getByLabel('Appearance').inputValue(),'light');assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'light');await page.getByLabel('Appearance').selectOption('spanvision-mono');record('theme-persistence',{width});
  await page.close();
 }
 const migrated=await browser.newPage();await migrated.addInitScript(()=>{localStorage.setItem('oss_settings',JSON.stringify({theme:'light',language:'en',remote_server_enabled:true,file_save_directory:'C:/Saved exports'}));localStorage.setItem('oss_dictionary',JSON.stringify({words:{Spanvision:'Spanvision infra'}}));localStorage.setItem('oss_samples_base','[[2,1]]');});await migrated.goto(base+'#settings');await migrated.getByLabel('Appearance').waitFor();assert.equal(await migrated.getByLabel('Appearance').inputValue(),'light');let imported=await migrated.evaluate(()=>JSON.parse(localStorage.getItem('spanvision_speech_settings')));assert.equal(imported.remote_server_enabled,false);assert.equal(imported.file_save_directory,'C:/Saved exports');assert.equal(await migrated.evaluate(()=>localStorage.getItem('sw_samples_base')),'[[2,1]]');await migrated.close();record('legacy-browser-migration');
 const retained=await browser.newPage();await retained.addInitScript(()=>{localStorage.setItem('spanvision_speech_settings',JSON.stringify({theme:'dark'}));localStorage.setItem('oss_settings',JSON.stringify({theme:'light'}));});await retained.goto(base+'#settings');assert.equal(await retained.getByLabel('Appearance').inputValue(),'dark');await retained.close();record('new-settings-win');
 const malformed=await browser.newPage();await malformed.addInitScript(()=>localStorage.setItem('oss_settings','bad JSON'));await malformed.goto(base+'#settings');assert.equal(await malformed.getByLabel('Appearance').inputValue(),'spanvision-mono');await malformed.close();record('malformed-legacy-settings');
 const details=await browser.newPage({viewport:{width:320,height:740}});details.on('pageerror',error=>errors.push({message:error.message}));await details.goto(base+'#transcribe');await details.getByRole('button',{name:'Explore audio import'}).click();const audioDialog=details.getByRole('dialog');await audioDialog.locator('input[type=file]').setInputFiles({name:'unsupported.txt',mimeType:'text/plain',buffer:Buffer.from('Not audio')});assert.match(await audioDialog.getByRole('alert').innerText(),/supported/);assert.equal(await audioDialog.getByRole('button',{name:'Preview transcript',exact:true}).isDisabled(),true);await audioDialog.locator('input[type=file]').setInputFiles({name:'site-review-'+('long-file-name-'.repeat(15))+'.wav',mimeType:'audio/wav',buffer:Buffer.from('Preview never reads file bytes')});assert.equal(await audioDialog.getByRole('button',{name:'Preview transcript',exact:true}).isEnabled(),true);assert.ok(await audioDialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1));await details.keyboard.press('Escape');assert.equal(await audioDialog.isVisible(),false);record('import-invalid-long-filename-escape');
 await details.goto(base+'#login');await details.getByRole('textbox',{name:'Email address'}).fill('invalid');await details.locator('input[name=password]').fill('short');await details.getByRole('button',{name:'Preview account',exact:true}).click();assert.match(await details.getByRole('alert').innerText(),/email/);await details.getByRole('textbox',{name:'Email address'}).fill('test@example.test');await details.getByRole('button',{name:'Preview account',exact:true}).click();assert.match(await details.getByRole('alert').innerText(),/8 characters/);await details.getByRole('button',{name:'Preview account',exact:true}).focus();const focus=await details.getByRole('button',{name:'Preview account',exact:true}).evaluate(el=>({width:getComputedStyle(el).outlineWidth,color:getComputedStyle(el).outlineColor,height:el.getBoundingClientRect().height}));assert.notEqual(focus.width,'0px');assert.ok(focus.height>=44);record('login-validation-focus-touch');await details.close();
 for(const locale of ['en','nl','de','fr','es','pt','zh','ja','pl','tr','ko','it','ru','uk','cs','ro','hu','sv','da','no','fi','el','bg','hr','sk']){const localized=await browser.newPage({viewport:{width:390,height:844}});await localized.addInitScript(value=>localStorage.setItem('spanvision_speech_settings',JSON.stringify({ui_language:value})),locale);await localized.goto(base+'#settings');await localized.getByLabel('Appearance').waitFor();assert.doesNotMatch(await localized.locator('body').innerText(),/OpenAEC|Open Speech Studio|Impertio/i);await localized.close();record('localized-brand',{locale});}
 const photo=await browser.newPage({viewport:{width:1440,height:1000}});await photo.goto(base+'#landing');await photo.locator('.speech-photo').scrollIntoViewIfNeeded();await photo.locator('.speech-photo img').evaluate(img=>img.decode());await photo.screenshot({path:path.join(shots,'landing-photo-1440.png')});assert.ok(await photo.locator('.speech-photo img').evaluate(img=>img.naturalWidth>0));await photo.close();record('natural-color-photography');
 for(const query of ['overlay','meeting-indicator']){const overlay=await browser.newPage({viewport:{width:320,height:80}});overlay.on('pageerror',error=>errors.push({message:error.message}));await overlay.goto(base+'?'+query+'=true');await overlay.locator('[role=status]').waitFor({state:'attached'});const backgrounds=await overlay.evaluate(()=>['html','body','#app'].map(selector=>getComputedStyle(document.querySelector(selector)).backgroundColor));assert.deepEqual(backgrounds,['rgba(0, 0, 0, 0)','rgba(0, 0, 0, 0)','rgba(0, 0, 0, 0)']);await overlay.close();record('transparent-overlay-window',{query});}
 for(const theme of ['spanvision-mono','dark','light']){const contrastPage=await browser.newPage();await contrastPage.addInitScript(value=>localStorage.setItem('spanvision_speech_settings',JSON.stringify({theme:value})),theme);await contrastPage.goto(base+'#workspace');await contrastPage.getByRole('button',{name:'Load sample transcript'}).waitFor();const ratios=await contrastPage.evaluate(()=>{const rgb=color=>{const probe=document.createElement(String.fromCharCode(115,112,97,110));probe.style.color=color;document.body.append(probe);const result=getComputedStyle(probe).color.slice(4,-1).split(String.fromCharCode(44)).slice(0,3).map(Number);probe.remove();return result;};const lum=values=>values.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}).reduce((sum,v,i)=>sum+v*[.2126,.7152,.0722][i],0);const ratio=(a,b)=>{const x=lum(rgb(a)),y=lum(rgb(b));return(Math.max(x,y)+.05)/(Math.min(x,y)+.05);};const primary=getComputedStyle(document.querySelector('.preview-workspace .btn-primary'));const root=getComputedStyle(document.documentElement);const values=[ratio(primary.color,primary.backgroundColor),ratio(root.getPropertyValue('--theme-text-muted').trim(),root.getPropertyValue('--theme-bg').trim())];for(const state of ['done','installing','error']){const step=document.createElement('div');step.className='tts-step '+state;const number=document.createElement('span');number.className='tts-step-num';number.textContent='1';step.append(number);document.body.append(step);const style=getComputedStyle(number);values.push(ratio(style.color,style.backgroundColor));step.remove();}return values;});assert.ok(ratios.every(value=>value>=4.5),`${theme} text contrast: ${ratios}`);await contrastPage.close();record('palette-state-contrast',{theme,ratios});}
 const hub=await browser.newPage();await hub.goto('http://127.0.0.1:4230/#modules');const speech=hub.locator('[data-module=speech]');await speech.getByRole('link',{name:'Open Speech in a new tab'}).waitFor();assert.equal(await speech.locator('a').getAttribute('href'),base);await hub.close();record('suite-speech-launcher');
 assert.deepEqual(requests,[],'Unexpected speech or upstream service request');assert.deepEqual(errors,[],'Browser console errors');
}catch(error){errors.push({message:error.message});process.exitCode=1;}
finally{await browser.close();fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({results,errors,requests},null,2)+'\n');}
console.log(`${results.length} scenarios checked; ${errors.length} errors. See qa/speech/browser-results.json.`);
