# GENERATED by src-tauri/src/print_formulieren.rs - do not edit by hand.
# The paper size table and all logic live there; a unit test keeps this file equal to its output.
$ErrorActionPreference = 'Stop'

$OpdsPrinterName = 'Spanvision PDF Printer'
$OpdsLegacyName = 'pdf workspace'
$OpdsDriverName = 'Microsoft Print to PDF'
$OpdsMarkerKey = 'SOFTWARE\SpanvisionPDFPrinter\Forms'

# Paper sizes in thousandths of a millimetre (portrait: width x height).
$OpdsForms = @(
    @{ Name = 'A1'; Width = 594000; Height = 841000; Standard = $true },
    @{ Name = 'A0'; Width = 841000; Height = 1189000; Standard = $true },
    @{ Name = 'A3L'; Width = 297000; Height = 630000; Standard = $false },
    @{ Name = 'A2L'; Width = 420000; Height = 804000; Standard = $false },
    @{ Name = 'A1L'; Width = 594000; Height = 1051000; Standard = $false },
    @{ Name = 'A0L'; Width = 841000; Height = 1399000; Standard = $false }
)

$OpdsSource = @'
using System;
using System.Runtime.InteropServices;

namespace OpdsPrint
{
    public static class Spooler
    {
        [StructLayout(LayoutKind.Sequential)]
        private struct FormInfo1
        {
            public uint Flags;
            public IntPtr Name;
            public int Width;
            public int Height;
            public int Left;
            public int Top;
            public int Right;
            public int Bottom;
        }

        [StructLayout(LayoutKind.Sequential)]
        private struct PrinterDefaults
        {
            public IntPtr Datatype;
            public IntPtr DevMode;
            public uint DesiredAccess;
        }

        private const uint PrinterAllAccess = 0x000F000C;
        private const uint ServerAccessAdminister = 0x00000001;

        [DllImport("winspool.drv", EntryPoint = "OpenPrinterW", CharSet = CharSet.Unicode, SetLastError = true)]
        private static extern bool OpenPrinterWith(string name, out IntPtr handle, ref PrinterDefaults defaults);

        [DllImport("winspool.drv", EntryPoint = "OpenPrinterW", CharSet = CharSet.Unicode, SetLastError = true)]
        private static extern bool OpenPrinterPlain(string name, out IntPtr handle, IntPtr defaults);

        [DllImport("winspool.drv", SetLastError = true)]
        private static extern bool ClosePrinter(IntPtr handle);

        [DllImport("winspool.drv", EntryPoint = "AddFormW", SetLastError = true)]
        private static extern bool AddForm(IntPtr handle, uint level, ref FormInfo1 form);

        [DllImport("winspool.drv", EntryPoint = "DeleteFormW", CharSet = CharSet.Unicode, SetLastError = true)]
        private static extern bool DeleteForm(IntPtr handle, string name);

        [DllImport("winspool.drv", EntryPoint = "GetFormW", CharSet = CharSet.Unicode, SetLastError = true)]
        private static extern bool GetForm(IntPtr handle, string name, uint level, IntPtr buffer, uint size, out uint needed);

        [DllImport("winspool.drv", EntryPoint = "DeviceCapabilitiesW", CharSet = CharSet.Unicode, SetLastError = true)]
        private static extern int DeviceCapabilities(string device, string port, ushort capability, IntPtr output, IntPtr devMode);

        // An empty printer name opens the local print server itself.
        private static IntPtr Open(string printer, bool administer)
        {
            string name = String.IsNullOrEmpty(printer) ? null : printer;
            IntPtr handle;
            if (administer)
            {
                PrinterDefaults defaults = new PrinterDefaults();
                defaults.DesiredAccess = name == null ? ServerAccessAdminister : PrinterAllAccess;
                if (OpenPrinterWith(name, out handle, ref defaults)) return handle;
            }
            if (OpenPrinterPlain(name, out handle, IntPtr.Zero)) return handle;
            return IntPtr.Zero;
        }

        // null when no form has this name, else { flags, width, height } in
        // thousandths of a millimetre. Flags 0 = added by a user or a program.
        public static int[] Find(string printer, string name)
        {
            IntPtr handle = Open(printer, false);
            if (handle == IntPtr.Zero) throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());
            try
            {
                uint needed;
                GetForm(handle, name, 1, IntPtr.Zero, 0, out needed);
                if (needed == 0) return null;
                IntPtr buffer = Marshal.AllocHGlobal((int)needed);
                try
                {
                    if (!GetForm(handle, name, 1, buffer, needed, out needed)) return null;
                    FormInfo1 form = (FormInfo1)Marshal.PtrToStructure(buffer, typeof(FormInfo1));
                    return new int[] { (int)form.Flags, form.Width, form.Height };
                }
                finally { Marshal.FreeHGlobal(buffer); }
            }
            finally { ClosePrinter(handle); }
        }

        private static int AddOn(string printer, string name, int width, int height)
        {
            IntPtr handle = Open(printer, true);
            if (handle == IntPtr.Zero) return Marshal.GetLastWin32Error();
            IntPtr namePtr = Marshal.StringToHGlobalUni(name);
            try
            {
                FormInfo1 form = new FormInfo1();
                form.Flags = 0;
                form.Name = namePtr;
                form.Width = width;
                form.Height = height;
                form.Left = 0;
                form.Top = 0;
                form.Right = width;
                form.Bottom = height;
                if (AddForm(handle, 1, ref form)) return 0;
                int error = Marshal.GetLastWin32Error();
                return error == 0 ? -1 : error;
            }
            finally
            {
                Marshal.FreeHGlobal(namePtr);
                ClosePrinter(handle);
            }
        }

        public static bool IsExists(int error)
        {
            return error == 80 || error == 183;
        }

        // 0 = added, else the Win32 error. Tried on the printer first and,
        // when that is refused, on the print server.
        public static int Add(string printer, string name, int width, int height)
        {
            int error = AddOn(printer, name, width, height);
            if (error != 0 && !IsExists(error) && !String.IsNullOrEmpty(printer))
            {
                int onServer = AddOn(null, name, width, height);
                if (onServer == 0 || IsExists(onServer)) return onServer;
            }
            return error;
        }

        private static int DeleteOn(string printer, string name)
        {
            IntPtr handle = Open(printer, true);
            if (handle == IntPtr.Zero) return Marshal.GetLastWin32Error();
            try
            {
                if (DeleteForm(handle, name)) return 0;
                int error = Marshal.GetLastWin32Error();
                return error == 0 ? -1 : error;
            }
            finally { ClosePrinter(handle); }
        }

        // 0 = removed, else the Win32 error.
        public static int Delete(string printer, string name)
        {
            int error = DeleteOn(printer, name);
            if (error != 0 && !String.IsNullOrEmpty(printer))
            {
                if (DeleteOn(null, name) == 0) return 0;
            }
            return error;
        }

        // Largest custom paper { width, length } in tenths of a millimetre,
        // or null when the driver does not report one.
        public static int[] MaxExtent(string printer)
        {
            int packed = DeviceCapabilities(printer, null, 5, IntPtr.Zero, IntPtr.Zero);
            if (packed == -1) return null;
            uint value = unchecked((uint)packed);
            int width = (int)(value & 0xFFFF);
            int length = (int)(value >> 16);
            if (width == 0 || length == 0) return null;
            return new int[] { width, length };
        }

        // Paper sizes the driver offers, flattened: width, length, width, ...
        // in tenths of a millimetre.
        public static int[] PaperSizes(string printer)
        {
            int count = DeviceCapabilities(printer, null, 3, IntPtr.Zero, IntPtr.Zero);
            if (count <= 0) return new int[0];
            IntPtr buffer = Marshal.AllocHGlobal(count * 8);
            try
            {
                count = Math.Min(count, DeviceCapabilities(printer, null, 3, buffer, IntPtr.Zero));
                if (count <= 0) return new int[0];
                int[] sizes = new int[count * 2];
                Marshal.Copy(buffer, sizes, 0, count * 2);
                return sizes;
            }
            finally { Marshal.FreeHGlobal(buffer); }
        }

        // Paper names the driver offers (what other programs show).
        public static string[] PaperNames(string printer)
        {
            int count = DeviceCapabilities(printer, null, 16, IntPtr.Zero, IntPtr.Zero);
            if (count <= 0) return new string[0];
            IntPtr buffer = Marshal.AllocHGlobal(count * 64 * 2);
            try
            {
                count = Math.Min(count, DeviceCapabilities(printer, null, 16, buffer, IntPtr.Zero));
                if (count <= 0) return new string[0];
                string[] names = new string[count];
                for (int i = 0; i < count; i++)
                {
                    string name = Marshal.PtrToStringUni(new IntPtr(buffer.ToInt64() + i * 128), 64);
                    int end = name.IndexOf('\0');
                    names[i] = (end >= 0 ? name.Substring(0, end) : name).Trim();
                }
                return names;
            }
            finally { Marshal.FreeHGlobal(buffer); }
        }
    }
}
'@

function Initialize-OpdsSpooler {
    if (-not ('OpdsPrint.Spooler' -as [type])) { Add-Type -TypeDefinition $OpdsSource -Language CSharp }
}

# The registry key that lists the forms this program added. Mode 'read',
# 'write' (null when the key is not there) or 'create'. Always the 64-bit
# view, also from the 32-bit installer.
function Open-OpdsMarker([string]$Mode) {
    $base = [Microsoft.Win32.RegistryKey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::LocalMachine, [Microsoft.Win32.RegistryView]::Registry64)
    if ($Mode -eq 'create') { return $base.CreateSubKey($OpdsMarkerKey) }
    return $base.OpenSubKey($OpdsMarkerKey, ($Mode -eq 'write'))
}

function Get-OpdsSizeText($Form) {
    return "$($Form.Name) ($($Form.Width / 1000) x $($Form.Height / 1000) mm)"
}

# Does the form fit the largest custom paper of the driver? An unknown
# maximum counts as fitting: the driver then decides for itself.
function Test-OpdsFits($MaxExtent, $Form) {
    if ($null -eq $MaxExtent) { return $true }
    return (($Form.Width / 100) -le $MaxExtent[0]) -and (($Form.Height / 100) -le $MaxExtent[1])
}

# Positions in the paper list of the driver that have this size (under any
# name), within 1 mm. $Sizes = width, length, width, ... in tenths of a mm.
function Get-OpdsDriverMatches($Sizes, $Form) {
    $w = $Form.Width / 100
    $h = $Form.Height / 100
    $hits = @()
    for ($i = 0; $i + 1 -lt $Sizes.Length; $i += 2) {
        $a = [Math]::Min($Sizes[$i], $Sizes[$i + 1])
        $b = [Math]::Max($Sizes[$i], $Sizes[$i + 1])
        if (([Math]::Abs($a - $w) -le 10) -and ([Math]::Abs($b - $h) -le 10)) { $hits += ($i / 2) }
    }
    return ,$hits
}

# The same size within 1 mm? Forms that come from a driver are often rounded.
function Test-OpdsSameSize($Found, $Form) {
    return ([Math]::Abs($Found[1] - $Form.Width) -le 1000) -and ([Math]::Abs($Found[2] - $Form.Height) -le 1000)
}

# Adds the missing forms. Never changes or replaces an existing form.
# Returns the number of forms that could not be added.
function Add-OpdsForms([string]$Printer) {
    $failed = 0
    $max = [OpdsPrint.Spooler]::MaxExtent($Printer)
    $sizes = [OpdsPrint.Spooler]::PaperSizes($Printer)
    foreach ($form in $OpdsForms) {
        $text = Get-OpdsSizeText $form
        if (-not (Test-OpdsFits $max $form)) {
            Write-Host "Paper size ${text}: skipped, larger than the maximum of '$Printer' ($($max[0] / 10) x $($max[1] / 10) mm)."
            continue
        }
        $found = [OpdsPrint.Spooler]::Find($Printer, $form.Name)
        if ($null -ne $found) {
            if (Test-OpdsSameSize $found $form) {
                Write-Host "Paper size ${text}: already present."
            } else {
                Write-Host "Paper size ${text}: a form named '$($form.Name)' with another size ($($found[1] / 1000) x $($found[2] / 1000) mm) exists; left unchanged."
            }
            continue
        }
        if ($form.Standard -and ((Get-OpdsDriverMatches $sizes $form).Length -gt 0)) {
            Write-Host "Paper size ${text}: the driver already offers this size."
            continue
        }
        $err = [OpdsPrint.Spooler]::Add($Printer, $form.Name, $form.Width, $form.Height)
        if ($err -eq 0) {
            $key = Open-OpdsMarker 'create'
            $key.SetValue($form.Name, "$($form.Width)x$($form.Height)")
            $key.Close()
            Write-Host "Paper size ${text}: added."
        } elseif ([OpdsPrint.Spooler]::IsExists($err)) {
            Write-Host "Paper size ${text}: already exists."
        } else {
            $failed++
            Write-Host "Paper size ${text}: could not be added (Windows error $err)."
        }
    }
    return $failed
}

# Removes only the forms this program added itself (listed in the registry)
# and only while they still are what was added. Returns the number of forms
# that could not be removed.
function Remove-OpdsForms([string]$Printer) {
    $failed = 0
    $key = Open-OpdsMarker 'write'
    if ($null -eq $key) {
        Write-Host "No paper sizes were added by pdf workspace."
        return 0
    }
    foreach ($form in $OpdsForms) {
        $text = Get-OpdsSizeText $form
        $mark = $key.GetValue($form.Name, $null)
        if ($null -eq $mark) { continue }
        $found = [OpdsPrint.Spooler]::Find($Printer, $form.Name)
        if ($null -eq $found) {
            $key.DeleteValue($form.Name, $false)
            continue
        }
        if (($found[0] -ne 0) -or ($found[1] -ne $form.Width) -or ($found[2] -ne $form.Height) -or ($mark -ne "$($form.Width)x$($form.Height)")) {
            $key.DeleteValue($form.Name, $false)
            Write-Host "Paper size ${text}: changed since it was added; left in place."
            continue
        }
        $err = [OpdsPrint.Spooler]::Delete($Printer, $form.Name)
        if ($err -eq 0) {
            $key.DeleteValue($form.Name, $false)
            Write-Host "Paper size ${text}: removed."
        } else {
            $failed++
            Write-Host "Paper size ${text}: could not be removed (Windows error $err)."
        }
    }
    $left = $key.ValueCount
    $key.Close()
    if ($left -eq 0) {
        $base = [Microsoft.Win32.RegistryKey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::LocalMachine, [Microsoft.Win32.RegistryView]::Registry64)
        $base.DeleteSubKey($OpdsMarkerKey, $false)
        $parent = Split-Path $OpdsMarkerKey -Parent
        $parentKey = $base.OpenSubKey($parent, $false)
        if (($null -ne $parentKey) -and ($parentKey.SubKeyCount -eq 0) -and ($parentKey.ValueCount -eq 0)) {
            $parentKey.Close()
            $base.DeleteSubKey($parent, $false)
        }
    }
    return $failed
}

# Which of our printers is there to talk to the print server through?
# Empty = the print server itself.
function Get-OpdsFormPrinter {
    foreach ($name in @($OpdsPrinterName, $OpdsLegacyName)) {
        if (Get-Printer -Name $name -ErrorAction SilentlyContinue) { return $name }
    }
    return ''
}

function Uninstall-OpdsPrinter {
    # Paper sizes first: removing them needs a printer or the print server.
    try {
        Initialize-OpdsSpooler
        $failed = Remove-OpdsForms (Get-OpdsFormPrinter)
        if ($failed -gt 0) { Write-Host "Note: $failed paper size(s) could not be removed." }
    } catch {
        Write-Host "Note: the extra paper sizes could not be removed. $($_.Exception.Message)"
    }

    # Both names, and only printers that use our driver.
    foreach ($name in @($OpdsPrinterName, $OpdsLegacyName)) {
        $printer = Get-Printer -Name $name -ErrorAction SilentlyContinue
        if ($null -eq $printer) { continue }
        if ($printer.DriverName -ne $OpdsDriverName) {
            Write-Host "'$name' uses another driver ('$($printer.DriverName)'); left unchanged."
            continue
        }
        Remove-Printer -Name $name
        Write-Host "Removed '$name'."
    }

    # Ports that only our printers used; a port that is still in use stays.
    Get-PrinterPort | Where-Object {
        $_.Name -like '*SpanvisionPDFWorkspace*print-capture*' -or $_.Name -like '*SpanvisionPDFPrinter*print-capture*' -or $_.Name -like '*\SpanvisionPDFPrinter\spool\latest.pdf'
    } | ForEach-Object {
        try { Remove-PrinterPort -Name $_.Name -ErrorAction Stop } catch {}
    }
}

Uninstall-OpdsPrinter
