// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Internal forces at a point along a beam.
 * Sign convention: N positive = tension; My positive = bottom fibre tension.
 * Units: kN (forces), kNm (moments).
 */
export type InternalForces = { n_ed: number, vy_ed: number, vz_ed: number, mt_ed: number, my_ed: number, mz_ed: number, };
