// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LateralBracing = { top_flange_positions: Array<number>, bottom_flange_positions: Array<number>, };
