// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoadFactors = { name: string, gamma_g: number, gamma_q: number, gamma_q_acc: number, psi0: number, };
