// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileGeometry = { h: number, b: number, tw: number, tf: number, t: number, r: number, };
