// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BeamCheckResult } from "./BeamCheckResult";

export type ReportInput = { project_name: string, project_number: string, engineer: string, company: string, date: string, steel_check_results: Array<BeamCheckResult>, };
