// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * All cross-sectional properties needed for EN 1993 checks.
 * Units: mm² for areas, mm⁴ for I, mm³ for W, mm for radii.
 */
export type SectionProperties = { area_mm2: number, iy_mm4: number, iz_mm4: number, wel_y_mm3: number, wel_z_mm3: number, wpl_y_mm3: number, wpl_z_mm3: number, av_y_mm2: number, av_z_mm2: number, it_mm4: number, iw_mm6: number, iy_radius_mm: number, iz_radius_mm: number, h_mm: number, b_mm: number, tw_mm: number, tf_mm: number, r_mm: number, };
