import fs from 'node:fs';
import ts from '../../calc-workspace/node_modules/typescript/lib/typescript.js';
const base='spanvision-pdf-workspace/open-pdf-studio/js/';
const names=[
 'Fire protection installation','Fire alarm control panel (BMC)','Fire alarm component','Fire service entrance','Fire service panel','Automatic detector','Heat detector','Smoke detector','Flame detector','Flame detector (alternative)','Beam detector','Aspirating smoke detection','Gas detector','Multisensor detector','Manual call point','Visual alarm (strobe)','Audible alarm (siren)','Visual and audible alarm','Voice alarm system','Voice message','Door/window contact','Holding magnet','Door closer','Fire damper','Pressure relief damper','Smoke damper','Fire hose reel','Dry riser','Wet riser','Sprinkler system','Pendant sprinkler','Upright sprinkler','Sidewall sprinkler','Flush sprinkler','Fire suppression system','CO2 suppression system','Foam suppression system','Water suppression system','Powder suppression system','Fire protection network','Firefighting network','Ring network','Distribution network','Single door','Double door','Sliding door','Swing gate','Roller door (top)','Roller door (bottom)','Up-and-over door','Folding door','Serving hatch','Emergency exit door','Emergency luminaire','Self-contained emergency lighting','Escape route sign','Illuminated sign','Central emergency lighting','Anti-panic lighting','Workplace lighting','Safety lighting','Emergency power supply','Battery unit','Generator','UPS','Smoke and heat exhaust system','Roof smoke vent','Facade smoke vent','Duct smoke damper','Smoke and heat exhaust','Outside air supply','Pressurization system','Smoke exhaust control panel','Smoke detector (smoke exhaust)','Heat detector (smoke exhaust)','Manual call point (smoke exhaust)','Wind sensor','Mechanical smoke and heat exhaust','Smoke exhaust fan','Supply fan','Extract fan','Ventilation system','Water sprinkler system','Pendant sprinkler head','Upright sprinkler head','Sidewall sprinkler head','Flush sprinkler head','Alarm valve','Check valve','Shutoff valve','Underground fire hydrant','Above-ground fire hydrant','Pump connection','Sprinkler control station','Water supply','Water tank','Booster pump','Open water mist system','Closed water mist system','Jockey pump','Water motor gong'
];
const nen=base+'solid/data/nen1414Library.js';let text=fs.readFileSync(nen,'utf8');
const source=ts.createSourceFile(nen,text,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS),edits=[];let count=0;
function visit(n){if(ts.isVariableDeclaration(n)&&n.name.getText(source)==='NAMES'&&ts.isObjectLiteralExpression(n.initializer)){
 if(n.initializer.properties.length!==names.length)throw new Error(`Safety symbol count ${n.initializer.properties.length} != ${names.length}`);
 for(const p of n.initializer.properties)edits.push({start:p.initializer.getStart(source),end:p.initializer.end,value:JSON.stringify(names[count++])});
 }ts.forEachChild(n,visit);}visit(source);for(const e of edits.sort((a,b)=>b.start-a.start))text=text.slice(0,e.start)+e.value+text.slice(e.end);fs.writeFileSync(nen,text);
const electricNames=['2× sockets','3× sockets','Socket','Earthed socket','Childproof socket','Socket with two-pole switch','Socket with two-pole interlock switch','Socket with safety transformer','Childproof earthed socket','Waterproof socket','Dimmer','Two-way dimmer switch','Three-pole switch','Single-pole switch','Single-pole switch with indicator lamp','Single-pole switch with delayed opening','Single-pole series switch','Single-pole two-way switch','Intermediate switch','Switch','Switch with permanent indicator lamp','Two-pole switch','Two-pole two-way switch','Emergency lighting','Self-contained emergency lighting','Luminaire','Luminaire with single-pole switch','Wall luminaire','Wired conduit','Dual data outlet','Empty conduit','Push button','Bell','Meter cabinet','Motion detector','Extractor hood (AFZ)','Boiler (B)','Fire alarm control panel (BMC)','Central earth point (CAP)','Central antenna system (CAI)','Central heating (CV)','Data connection (D)','Doorbell (BEL)','Electric curtain control (EG)','Intercom (IC)','Refrigerator (KK)','Cooker (KT)','Microwave (MAGN)','Mechanical ventilation (MV)','Smoke detector (RM)','Telecom connection (TEL)','Thermostat (TH)','Dishwasher (VW)','Freezer (VK)','Heat pump / boiler (WPB)','Tumble dryer (WD)','Washing machine (WM)','Sun shading (ZW)'];
const electric=base+'solid/data/elektraSymbols.js';let electricText=fs.readFileSync(electric,'utf8');let i=0;electricText=electricText.replace(/"name":"[^"\n]+"/g,()=>`"name":${JSON.stringify(electricNames[i++])}`);if(i!==electricNames.length)throw new Error('Electrical symbol count mismatch');fs.writeFileSync(electric,electricText);
const map={'Wand (IfcWall)':'Wall (IfcWall)','Vliesgevel (IfcCurtainWall)':'Curtain wall (IfcCurtainWall)','Kozijn (IfcWindow)':'Window (IfcWindow)','Ruimte (IfcSpace)':'Space (IfcSpace)','Kanaalplaatvloer':'Hollow-core slab','Isolatieplaatvloer':'Insulated slab','PS-isolatievloer':'EPS insulated floor','Koker':'Hollow section','Hoeklijn':'Angle section','Houten balk':'Timber beam','Bout / anker (M6–M24)':'Bolt / anchor (M6–M24)','Wapeningskorf (section)':'Reinforcement cage (section)','Wapeningsstaaf':'Reinforcement bar','Netwapening':'Mesh reinforcement','Paalpuntniveau':'Pile tip level','Overspanningspijl vloer':'Floor span arrow','Stenenrij (lagen-/koppenmaat)':'Brick courses (course/width module)','Stavenreeks (wapening)':'Reinforcement bar series','Betonbalk (IfcBeam)':'Concrete beam (IfcBeam)','Systeemraster (IfcCovering)':'Panel grid (IfcCovering)','Systeemplafond (IfcCovering.CEILING)':'Suspended ceiling (IfcCovering.CEILING)','Stramien':'Grid line','Peilmaat (spot elevation)':'Spot elevation','Oplegging (steunpunt)':'Support','Puntlast':'Point load','q-last (verdeelde belasting)':'q-load (distributed load)','Beddingsveren':'Foundation springs','Windverband':'Wind bracing','Scharnierverbinding':'Pinned connection','Maskeer (afdekvlak)':'Mask','Bouwkraan (zwenkstraal)':'Tower crane (slew radius)','Draaicirkel vrachtwagen':'Truck turning circle','Parkeervak':'Parking space','Bouwkeet':'Site cabin','Wandcloset':'Wall-mounted toilet','Staand closet':'Floor-mounted toilet','Fontein':'Hand basin','Hoekfontein':'Corner hand basin','Aanrecht (strekkende meter)':'Countertop (linear meter)','Aanrecht hoekopstelling (L)':'L-shaped countertop','Kookeiland':'Kitchen island'};
const nl=base+'solid/data/nlSymbolLibrary.js';let nlText=fs.readFileSync(nl,'utf8');for(const [from,to]of Object.entries(map))nlText=nlText.replaceAll("name: '"+from+"'","name: "+JSON.stringify(to));fs.writeFileSync(nl,nlText);
const categories={'NL IFC Bouw':'NL IFC Construction','NL Elektra':'NL Electrical','NL Bouwplaats':'NL Construction site','NL Sanitair':'NL Plumbing','NL Keuken':'NL Kitchen','NL NEN 1414 — Brandbeveiliging':'NL NEN 1414 — Fire protection','NL NEN 1414 — Blussystemen':'NL NEN 1414 — Fire suppression','NL NEN 1414 — Deuren':'NL NEN 1414 — Doors','NL NEN 1414 — Noodverlichting':'NL NEN 1414 — Emergency lighting','NL NEN 1414 — Rook/Warmteafvoer':'NL NEN 1414 — Smoke/heat exhaust','NL NEN 1414 — Ventilatie':'NL NEN 1414 — Ventilation'};
fs.writeFileSync(base+'i18n/catalog.js','// English captions retain the original catalog identifiers.\nconst labels = '+JSON.stringify(categories,null,2)+';\nexport function catalogLabel(value) { return Object.hasOwn(labels, value) ? labels[value] : value; }\n');
const palette=base+'solid/components/SymbolPalette.jsx';let paletteText=fs.readFileSync(palette,'utf8');if(!paletteText.includes('import { catalogLabel }'))paletteText="import { catalogLabel } from '../../i18n/catalog.js';\n"+paletteText;paletteText=paletteText.replaceAll('{cat.name}','{catalogLabel(cat.name)}');fs.writeFileSync(palette,paletteText);
const view=base+'solid/components/ribbon/ViewTab.jsx';fs.writeFileSync(view,fs.readFileSync(view,'utf8').replaceAll('"Toolpalette"','"Tool palette"'));
for(const file of [base+'symbols/linework-catalog.js',base+'solid/data/symbolLibraryOnline.js','calc-workspace/src/App.tsx'])fs.writeFileSync(file,fs.readFileSync(file,'utf8').replaceAll('|| "and"',"|| 'en'"));
const prefs=base+'core/preferences.js';fs.writeFileSync(prefs,fs.readFileSync(prefs,'utf8').replace("changeLanguage(state.preferences.language || 'auto');","state.preferences.language = 'en';\n  changeLanguage('en');"));
console.log('Translated safety, electrical and construction symbol captions.');
