[package]
name = "pile-plan-wasm"
version = "0.4.2"
edition = "2021"
license = "LGPL-3.0-or-later"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3"
pile-plan-core = { path = "../pile-plan-core", default-features = false }
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
