// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForcePoint } from "../steel/ForcePoint";
import type { LoadDurationClass } from "./LoadDurationClass";
import type { LtbLoadCase } from "./LtbLoadCase";
import type { LtbLoadPosition } from "./LtbLoadPosition";
import type { ServiceClass } from "./ServiceClass";

/**
 * Invoer voor één houten staaf (rechthoekige doorsnede b × h).
 */
export type TimberBeamCheckInput = { beam_id: number, 
/**
 * Doorsnedebreedte b in mm.
 */
width_mm: number, 
/**
 * Doorsnedehoogte h in mm (buiging om de sterke as).
 */
height_mm: number, 
/**
 * Sterkteklasse, bijv. "C24" (EN 338) of "GL28h" (EN 14080).
 */
strength_class: string, 
/**
 * Klimaatklasse (service class) §2.3.1.3.
 */
service_class: ServiceClass, 
/**
 * Maatgevende belastingduurklasse van de UGT-combinatie (§3.1.3:
 * de kortst durende belasting in de combinatie bepaalt k_mod).
 */
load_duration: LoadDurationClass, 
/**
 * Staaflengte in m.
 */
length_m: number, 
/**
 * Krachtsverloop (envelop) langs de staaf; N drukt negatief.
 */
forces_envelope: Array<ForcePoint>, 
/**
 * Kniklengte om de sterke as (m).
 */
buckling_length_y_m: number, 
/**
 * Kniklengte om de zwakke as (m) — bij kipsteunen de steunafstand.
 */
buckling_length_z_m: number, 
/**
 * Kipsteunafstand (m) voor tabel 6.1; 0 → staaflengte.
 */
ltb_segment_length_m: number, 
/**
 * Belastinggeval voor l_ef (tabel 6.1).
 */
ltb_load_case: LtbLoadCase, 
/**
 * Aangrijpingspunt van de belasting (tabel 6.1, voetnoot).
 */
ltb_load_position: LtbLoadPosition, 
/**
 * Expliciete effectieve kiplengte in m; 0 → berekenen via tabel 6.1.
 */
ltb_effective_length_override_m: number, 
/**
 * Kiptoets §6.3.3 uitvoeren. De referentie-uitwerking voert 6.3.3
 * alleen voor de ligger uit, niet voor de kolommen.
 */
perform_ltb_check: boolean, 
/**
 * Scheurfactor k_cr voor dwarskracht (6.13a). 1,0 conform de
 * referentie-uitwerking; A1-aanbevolen waarde 0,67.
 */
k_cr: number, 
/**
 * Lastverdelend systeem aanwezig → k_sys = 1,1 (§6.6).
 */
load_sharing: boolean, 
/**
 * Zakking onder de karakteristieke BGT-combinatie (mm, negatief = omlaag).
 */
deflection_inst_mm: number, 
/**
 * Zakking onder de quasi-blijvende BGT-combinatie (mm).
 */
deflection_quasi_perm_mm: number, 
/**
 * Zakking onder de blijvende BGT-combinatie (mm).
 */
deflection_permanent_mm: number, 
/**
 * Noemer voor w_fin (L/n), NB-standaard 250.
 */
deflection_limit_fin: number, 
/**
 * Noemer voor w_add (L/n), NB-standaard 333.
 */
deflection_limit_add: number, };
