// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckStatus } from "../steel/CheckStatus";
import type { LoadDurationClass } from "./LoadDurationClass";
import type { NamedCheck } from "../steel/NamedCheck";
import type { ServiceClass } from "./ServiceClass";

/**
 * Volledig toetsresultaat van één houten staaf.
 */
export type TimberBeamCheckResult = { beam_id: number, 
/**
 * Doorsnedenaam, bijv. "96 x 450".
 */
section_name: string, 
/**
 * Sterkteklasse, bijv. "C24".
 */
strength_class: string, service_class: ServiceClass, load_duration: LoadDurationClass, checks: Array<NamedCheck>, uc_max: number, status: CheckStatus, governing_check_id: string, };
