import path from 'node:path';import fs from 'node:fs';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
process.env.TEMP='D:/SpanvisionToolchain/pile-temp';process.env.TMP=process.env.TEMP;
const root=process.cwd(),out=path.join(root,'qa/pile');const {chromium}=await import(pathToFileURL(path.join(root,'node_modules/playwright/index.mjs')));const browser=await chromium.launch({channel:'msedge',headless:true});const results=[];
try{const page=await browser.newPage({locale:'en-US',viewport:{width:1440,height:900}});await page.goto('http://127.0.0.1:4255/');await page.locator('.viewer-marker-hit-target').first().waitFor();
 const alignment=[];for(const width of [1440,820,390,320,1440]){await page.setViewportSize({width,height:900});await page.waitForTimeout(250);const result=await page.evaluate(()=>{const markers=[...document.querySelectorAll('.viewer-marker-hit-target')],graphics=[...document.querySelectorAll('.viewer-marker-graphic')];const points=graphics.map(g=>{const m=g.getAttribute('transform').match(/translate\(([^ ]+) ([^)]+)\)/);return {x:Number(m[1]),y:Number(m[2]),node:g};});return {width:innerWidth,compared:markers.length,maxError:Math.max(...markers.map(button=>{const g=points.find(p=>Math.abs(p.x-parseFloat(button.style.left))<.01&&Math.abs(p.y-parseFloat(button.style.top))<.01);if(!g)return 1e6;const p=new DOMPoint(0,0).matrixTransform(g.node.getScreenCTM());const r=button.getBoundingClientRect();return Math.hypot(p.x-(r.x+r.width/2),p.y-(r.y+r.height/2));}))};});assert.ok(result.maxError<1);alignment.push(result);}results.push({name:'Drawing/hit-target alignment after resizing',status:'passed',evidence:alignment});
 await page.getByRole('button',{name:'Preferences',exact:true}).click();await page.getByRole('button',{name:'About',exact:true}).click();await page.getByRole('button',{name:'Open-source Notices',exact:true}).click();const notices=page.locator('.legal-notices');await notices.waitFor();assert.match(await notices.innerText(),/OpenAEC Foundation/);await notices.locator('summary').filter({hasText:'Dependency notices and licenses'}).click();const react=notices.locator('details').filter({has:page.locator('summary').filter({hasText:/^react 19/})}).last();await react.locator('summary').first().click();await page.waitForTimeout(300);assert.match(await react.innerText(),/Copyright|Permission is hereby granted/);await page.screenshot({path:path.join(out,'pile-notices.png')});results.push({name:'Accessible upstream, GNU, font and dependency notices',status:'passed'});
 const hub=await browser.newPage({viewport:{width:1440,height:900}});await hub.goto('http://127.0.0.1:4230/#modules');const link=hub.locator('[data-module="pile"] a');await link.waitFor();assert.equal(await link.getAttribute('href'),'http://127.0.0.1:4255/');await hub.screenshot({path:path.join(out,'hub-pile-launcher.png'),fullPage:true});await hub.goto('http://127.0.0.1:4230/#landing');const photo=hub.locator('.photo img');await photo.scrollIntoViewIfNeeded();await hub.waitForFunction(()=>document.querySelector('.photo img').complete);const natural=await photo.evaluate(e=>({filter:getComputedStyle(e).filter,loaded:e.naturalWidth>0}));assert.equal(natural.filter,'none');assert.ok(natural.loaded);await hub.evaluate(()=>scrollTo(0,0));await hub.screenshot({path:path.join(out,'hub-landing-1440.png'),fullPage:true});results.push({name:'PPW hub launcher and natural-color business photography',status:'passed',evidence:natural});
 const health=await(await fetch('http://127.0.0.1:4255/__pile/status')).json();assert.equal(health.available,true);results.push({name:'Stamped preview health',status:'passed',evidence:health});
}finally{await browser.close();fs.writeFileSync(path.join(out,'final-checks.json'),JSON.stringify({results},null,2)+'\n');}
