import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {pathToFileURL} from 'node:url';
process.env.TEMP='D:/SpanvisionToolchain/pile-temp';process.env.TMP=process.env.TEMP;
const root=process.cwd(),out=path.join(root,'qa/pile'),exe=path.join(root,'delivery/pile/windows/spanvision-pile-plane-workspace.exe');
const {chromium}=await import(pathToFileURL(path.join(root,'node_modules/playwright/index.mjs')));
const child=spawn(exe,[],{env:{...process.env,WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:'--remote-debugging-port=9255'},windowsHide:false,stdio:'ignore'});
let browser;const result={method:'Packaged executable with process-local WebView2 CDP for QA only',results:[],errors:[]};
try{let ready=false;for(let attempt=0;attempt<20;attempt++){try{const response=await fetch('http://127.0.0.1:9255/json/version');if(response.ok){ready=true;break;}}catch{}await new Promise(resolve=>setTimeout(resolve,500));}assert.ok(ready,'Native WebView2 did not expose its QA endpoint');
 browser=await chromium.connectOverCDP('http://127.0.0.1:9255');const pages=browser.contexts().flatMap(c=>c.pages());const page=pages.find(p=>/tauri\.localhost|tauri:\/\//.test(p.url()))||pages[0];assert.ok(page);page.on('pageerror',e=>result.errors.push(String(e)));await page.locator('.viewer-marker-hit-target').first().waitFor({timeout:60000});
 assert.equal(await page.title(),'Pile Plane Workspace — Spanvision infra');assert.equal(await page.evaluate(()=>Boolean(window.__TAURI_INTERNALS__)),true);const startup=await page.locator('.project-explorer').innerText();assert.match(startup,/328/);assert.match(startup,/77/);assert.match(startup,/2340/);result.results.push({name:'Native adapter sample startup and branded title',status:'passed',evidence:{url:page.url(),theme:await page.locator('html').getAttribute('data-theme'),startup}});await page.screenshot({path:path.join(out,'pile-windows.png')});
 await page.getByRole('button',{name:'Preferences',exact:true}).click();await page.getByRole('button',{name:'About',exact:true}).click();await page.getByRole('button',{name:'Open-source Notices',exact:true}).click();assert.match(await page.locator('.legal-notices').innerText(),/OpenAEC Foundation/);await page.screenshot({path:path.join(out,'pile-windows-notices.png')});result.results.push({name:'Native open-source notices',status:'passed'});
}catch(e){result.errors.push(String(e));process.exitCode=1;console.error(e);}finally{if(browser)await browser.close();child.kill();fs.writeFileSync(path.join(out,'native-smoke.json'),JSON.stringify(result,null,2)+'\n');}
