[package]
name = "nen-en-1993-1-1-section"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
nationale-bijlage = { path = "../nationale-bijlage" }
serde = { workspace = true }
ts-rs = { workspace = true }
mechanics = { path = "../mechanics" }
section-properties = { path = "../section-properties" }
nen-en-1990 = { path = "../nen-en-1990" }

[dev-dependencies]
approx = { workspace = true }
insta = { workspace = true }
steel-profiles = { path = "../steel-profiles" }
