// Generated by branding/sync.mjs.
use iced::Color;
pub const PAGE: Color = Color { r: 0.0 / 255.0, g: 0.0 / 255.0, b: 0.0 / 255.0, a: 1.0 };
pub const SURFACE: Color = Color { r: 18.0 / 255.0, g: 18.0 / 255.0, b: 18.0 / 255.0, a: 1.0 };
pub const SURFACE_RAISED: Color = Color { r: 27.0 / 255.0, g: 27.0 / 255.0, b: 27.0 / 255.0, a: 1.0 };
pub const SURFACE_HOVER: Color = Color { r: 32.0 / 255.0, g: 32.0 / 255.0, b: 32.0 / 255.0, a: 1.0 };
pub const CANVAS: Color = Color { r: 27.0 / 255.0, g: 27.0 / 255.0, b: 27.0 / 255.0, a: 1.0 };
pub const TEXT: Color = Color { r: 255.0 / 255.0, g: 255.0 / 255.0, b: 255.0 / 255.0, a: 1.0 };
pub const TEXT_SOFT: Color = Color { r: 238.0 / 255.0, g: 238.0 / 255.0, b: 238.0 / 255.0, a: 1.0 };
pub const TEXT_MUTED: Color = Color { r: 153.0 / 255.0, g: 153.0 / 255.0, b: 153.0 / 255.0, a: 1.0 };
pub const CANVAS_RGB: [u8;3] = [27,27,27];
pub const BORDER: Color = Color { r: 1.0, g: 1.0, b: 1.0, a: 0.16 };
pub const FOCUS: Color = Color { r: 1.0, g: 1.0, b: 1.0, a: 0.58 };
