import { createSignal, createEffect, For, Show, onCleanup } from "solid-js";
import brand from "../brand.json";
import { runtime } from "../lib/runtime";

export const SAMPLE="The site review is scheduled for Thursday at nine. Please bring the revised foundation drawings and confirm the access route before the meeting. We will record the decisions and share the final notes with the project team.";
const [profile,setProfile]=createSignal({name:"Alex Morgan",email:"alex@example.test"});
function Arrow(){return <span aria-hidden="true">↗</span>;}
function Waveform(){const levels=[8,12,22,15,35,48,25,57,74,40,90,58,32,65,97,70,44,83,60,35,20,45,73,98,61,35,68,89,46,72,55,28,45,70,38,52,75,41,26,60,83,53,36,67,90,59,40,24,48,31,62,43,29,15,24,13];return <div class="sample-waveform" aria-hidden="true"><For each={levels}>{height=><i style={{height:`${height}%`}}/>}</For></div>;}

export function PreviewWorkspace(props:{text:string;onChange:(text:string)=>void}){
  const [message,setMessage]=createSignal("");
  return <section class="preview-workspace"><div class="page-heading"><div><span class="eyebrow">YOUR WORDS, IN FOCUS</span><h1>Speech workspace</h1></div><span class="small-label">Sample transcript</span></div>
    <Show when={props.text} fallback={<div class="empty-state"><div class="empty-icon">SW</div><h2>Ready for your next idea.</h2><p>Explore a sample transcript, or open the desktop app to dictate with a local model.</p><button class="btn btn-primary btn-large" onClick={()=>props.onChange(SAMPLE)}>Load sample transcript <Arrow/></button><a class="text-link" href="#transcribe">Explore audio import</a></div>}>
      <div class="sample-session"><span class="small-label">SITE BRIEFING / SAMPLE AUDIO</span><Waveform/><div class="sample-session-meta"><span>00:18</span><span>English · Sample transcript</span></div></div>
      <div class="transcript-toolbar"><span>TRANSCRIPT</span><div><button class="btn btn-small" onClick={async()=>{try{await navigator.clipboard.writeText(props.text);setMessage("Transcript copied.");}catch{setMessage("Select the transcript and copy it manually.");}}}>Copy</button><button class="btn btn-small" onClick={()=>{const url=URL.createObjectURL(new Blob([props.text],{type:"text/plain"}));const link=document.createElement("a");link.href=url;link.download="speech-workspace-transcript.txt";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage("Transcript exported.");}}>Export text</button><button class="btn btn-small" onClick={()=>props.onChange("")}>Clear</button></div></div>
      <textarea class="sample-transcript" aria-label="Edit sample transcript" value={props.text} onInput={e=>props.onChange(e.currentTarget.value)}/><p class="small-label">Edit your words. Copy or export when you are ready.</p>
    </Show><Show when={message()}><p role="status" class="form-message">{message()}</p></Show>
  </section>;
}

export function AudioImport(props:{onSample:(text:string)=>void;compact?:boolean}){
  const [filename,setFilename]=createSignal("site-briefing.wav");const [state,setState]=createSignal<"ready"|"processing"|"complete">("ready");const [progress,setProgress]=createSignal(0);const [error,setError]=createSignal("");
  let dialog!:HTMLDialogElement;let previousFocus:HTMLElement|null=null;let timer:ReturnType<typeof setInterval>|undefined;
  const clear=()=>{if(timer)clearInterval(timer);timer=undefined;};
  const close=()=>{clear();dialog.close();previousFocus?.focus();};
  const open=(event:MouseEvent)=>{previousFocus=event.currentTarget as HTMLElement;setState("ready");setProgress(0);setError("");dialog.showModal();};
  const start=()=>{clear();setState("processing");setProgress(0);timer=setInterval(()=>{const next=Math.min(100,progress()+10);setProgress(next);if(next===100){clear();setState("complete");}},100);};
  onCleanup(clear);
  function trap(event:KeyboardEvent){if(event.key!=="Tab")return;const elements=Array.from(dialog.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),a[href]')).filter(item=>item.getClientRects().length);const first=elements[0],last=elements[elements.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}
  return <><Show when={!props.compact}><div class="page-heading"><div><span class="eyebrow">FROM AUDIO TO ACTION</span><h1>Audio import</h1><p>Turn recordings into words you can review, refine, and share.</p></div></div><div class="audio-import-card"><span class="import-glyph" aria-hidden="true">↥</span><h2>A clearer record.</h2><p>WAV, MP3, FLAC, M4A, AAC, and supported video recordings.<br/>Local file transcription runs in the desktop app.</p><button class="btn btn-primary" onClick={open}>Explore audio import <Arrow/></button><span class="small-label">Browser preview · sample transcript · no audio upload</span></div></Show>
    <Show when={props.compact}><button class="btn btn-outline" onClick={open}>Explore audio import <Arrow/></button></Show>
    <dialog ref={dialog} class="speech-dialog" aria-labelledby="audio-import-title" onKeyDown={trap} onCancel={event=>{event.preventDefault();close();}}><div class="dialog-heading"><div><span class="eyebrow">SPEECH WORKSPACE</span><h2 id="audio-import-title">Audio import preview</h2></div><button class="btn icon-button" aria-label="Close audio import" onClick={close}>×</button></div>
      <p>This browser preview uses a sample transcript. Selected audio is never read, processed, or uploaded.</p>
      <Show when={state()==="ready"}><label class="file-picker">Choose audio<input type="file" accept=".wav,.mp3,.flac,.m4a,.aac,.ogg,.opus,.webm,.mp4,.mkv,.mov" onChange={event=>{const file=event.currentTarget.files?.[0];if(!file)return;if(!/\.(wav|mp3|flac|m4a|aac|ogg|opus|webm|mp4|mkv|mov)$/i.test(file.name)){setError("Choose a supported audio or video file.");return;}setFilename(file.name);setError("");}}/></label><div class="selected-file">{filename()}<span>Sample transcript will be shown</span></div></Show>
      <Show when={state()==="processing"}><div role="status">Preparing sample transcript… {progress()}%</div><progress aria-label="Sample transcript progress" value={progress()} max="100"/></Show>
      <Show when={state()==="complete"}><p role="status">Preview complete. Your sample transcript is ready.</p><div class="sample-excerpt">{SAMPLE}</div></Show>
      <Show when={error()}><p role="alert" class="form-message">{error()}</p></Show>
      <div class="dialog-actions"><button class="btn btn-outline" onClick={close}>{state()==="complete"?"Close":"Cancel"}</button><Show when={state()==="ready"}><button class="btn btn-primary" disabled={!!error()} onClick={start}>Preview transcript</button></Show><Show when={state()==="complete"}><button class="btn btn-primary" onClick={()=>{close();props.onSample(SAMPLE);}}>Open sample transcript <Arrow/></button></Show></div>
    </dialog>
  </>;
}

export default function BrandPages(props:{view:string;navigate:(value:string)=>void;onSample:(text:string)=>void}){
  const [error,setError]=createSignal("");const [success,setSuccess]=createSignal("");
  createEffect(()=>{props.view;setError("");setSuccess("");});
  function submit(event:SubmitEvent){event.preventDefault();const form=event.currentTarget as HTMLFormElement;const data=new FormData(form);setError("");const name=String(props.view==="signup"?data.get("name")||"":profile().name).trim();const email=String(data.get("email")||"").trim();const password=String(data.get("password")||"");if(props.view==="signup"&&!name){setError("Enter your name.");return;}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){setError("Enter a valid email address.");return;}if(password.length<8){setError("Use at least 8 characters for the preview password.");return;}setProfile({name,email});form.reset();props.navigate("account");}
  const suggestions=[{number:"01",title:"Capture the thought.",text:"Dictate a site note while the detail is still fresh.",route:"home",label:"Open speech workspace"},{number:"02",title:"Keep every decision.",text:"Review the meeting workflow for microphone and system audio.",route:"meeting",label:"Explore meetings"},{number:"03",title:"Give recordings a voice.",text:"Import audio and refine the words in your transcript workspace.",route:"transcribe",label:"Explore audio import"}];
  return <>
    <Show when={props.view==="landing"}><div class="speech-landing"><nav class="landing-nav" aria-label="Speech workspace links"><a href="#workspace">Workspace</a><a href="#suggestions">Suggestions</a><a href="#about">About</a><a href="#login">Account preview</a></nav>
      <section class="speech-hero"><span class="eyebrow"><i class="mono-dot"/> SPANVISION INFRA / SPEECH TOOLS</span><h1>Your voice.<br/>A clearer<br class="mobile-break"/> workspace<span>.</span></h1><div class="hero-bottom"><p>Ideas, recordings, and decisions.<br/>Bring your words into focus.</p><div class="hero-actions"><a class="btn btn-primary" href="#workspace">Open workspace <Arrow/></a><AudioImport compact onSample={props.onSample}/><span class="small-label">Local speech. Familiar workflows. No account needed.</span></div></div>
      <a class="landing-transcript" href="#workspace" aria-label="Explore the speech workspace"><div class="transcript-window-bar"><span><img src="/sw-mark.svg" alt=""/> {brand.product}</span><span>SITE BRIEFING / SAMPLE</span></div><div class="landing-wave"><Waveform/><div><span>00:18</span><span>SAMPLE TRANSCRIPT</span></div></div><p>“Please bring the revised foundation drawings and confirm the access route before the meeting.”</p><footer><span>DICTATE · TRANSCRIBE · REFINE</span><Arrow/></footer></a><div class="hero-caption"><span>YOUR WORDS. ON YOUR COMPUTER.</span><span>SPEECH / MEETINGS / RECORDINGS</span></div></section>
      <section class="speech-features"><div><span class="eyebrow">BUILT FOR THE WAY YOU WORK</span><h2>Speak naturally.<br/>Work clearly.</h2></div><div><For each={suggestions}>{item=><a href={`#${item.route==="home"?"workspace":item.route}`}><span>/{item.number}</span><h3>{item.title}</h3><p>{item.text}</p><Arrow/></a>}</For></div></section>
      <section class="speech-photo"><img src="https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=85" alt="Business workspace with naturally colored desks and greenery" loading="lazy"/><div><span class="eyebrow">MADE FOR REAL PROJECTS</span><h2>Keep the detail.<br/>Clear the noise.</h2><p>Capture site notes, project meetings, and the ideas that connect them. Your desktop app processes speech locally with models you control.</p><a class="btn btn-outline" href="#suggestions">Find your next step <Arrow/></a></div></section><footer class="landing-footer"><span>{brand.organization} / {brand.product}</span><a href="#about">About & open-source notices</a></footer>
    </div></Show>
    <Show when={props.view==="suggestions"}><section class="speech-page"><span class="eyebrow">A BETTER NEXT STEP</span><h1>Start with your voice.</h1><p>Choose the workflow that fits the moment.</p><div class="suggestion-grid"><For each={suggestions}>{item=><article><span class="eyebrow">/{item.number}</span><h2>{item.title}</h2><p>{item.text}</p><a class="btn btn-outline" href={`#${item.route==="home"?"workspace":item.route}`}>{item.label} <Arrow/></a></article>}</For></div><p class="small-label">{runtime.preview?"Browser previews use sample data. Local speech processing is available in the desktop app.":"Local tools. No account required."}</p></section></Show>
    <Show when={props.view==="login"||props.view==="signup"}><section class="account-screen"><div class="account-intro"><span class="eyebrow">SPANVISION INFRA / ACCOUNT PREVIEW</span><h1>{props.view==="signup"?"Your next\nworkspace.":"Welcome\nback."}</h1><p>Explore your account experience.<br/>Your speech tools are ready without an account.</p><a href="#workspace" class="text-link">Return to speech workspace <Arrow/></a></div><form class="account-form" noValidate onSubmit={submit}><img src="/sw-mark.svg" alt="SW" width="44" height="44"/><h2>{props.view==="signup"?"Create an account preview":"Sign in preview"}</h2><p>Preview only. No credentials are saved or sent.</p><Show when={props.view==="signup"}><label>Full name<input name="name" autocomplete="off" /></label></Show><label>Email address<input name="email" type="email" autocomplete="off" /></label><label>Preview password<input name="password" type="password" autocomplete="off" /></label><Show when={error()}><p role="alert" class="form-message">{error()}</p></Show><button class="btn btn-primary" type="submit">Preview account <Arrow/></button><a class="text-link" href={props.view==="signup"?"#login":"#signup"}>{props.view==="signup"?"Already exploring? Sign in preview":"Create an account preview"}</a></form></section></Show>
    <Show when={props.view==="account"}><section class="speech-page"><span class="eyebrow">YOUR SPACE / ACCOUNT PREVIEW</span><h1>Hello, {profile().name.split(" ")[0]}.</h1><p>Preview settings stay in this session and reset when you reload.</p><form class="profile-form" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);const name=String(data.get("name")||"").trim();if(!name){setError("Enter a display name.");setSuccess("");return;}setProfile({...profile(),name});setError("");setSuccess("Preview changes saved for this session.");}}><div class="profile-avatar">{profile().name.charAt(0).toUpperCase()}</div><label>Display name<input name="name" value={profile().name} autocomplete="off"/></label><label>Email address<input value={profile().email} readOnly/></label><div class="profile-detail"><span>Speech processing</span><span>Local desktop · no subscription required</span></div><button class="btn btn-primary" type="submit">Save preview changes <Arrow/></button><Show when={error()}><p class="form-message" role="alert">{error()}</p></Show><Show when={success()}><p class="form-message" role="status">{success()}</p></Show></form><a class="text-link" href="#workspace">Open speech workspace <Arrow/></a></section></Show>
  </>;
}
