import { createSignal, onCleanup, For, Show } from 'solid-js';
import { render } from 'solid-js/web';
import { BRAND } from '../js/core/brand.js';
import Dialog from '../js/solid/components/Dialog.jsx';
import './preview.css';

function Arrow(props) { return <svg width={props.size || 18} height={props.size || 18} viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg>; }
function Mark() { return <a class="brand-lockup" href="#landing" aria-label="Spanvision Infra home"><img src="icon.svg" alt="GW"/><span>{BRAND.organization}<small>{BRAND.product}</small></span></a>; }
function Floorplan() { return <svg class="plan-art" viewBox="0 0 620 350" aria-label="Architectural drawing with its original blue and red annotations"><rect width="620" height="350" fill="#fff"/><g fill="none" stroke="#242424" stroke-width="3"><path d="M80 50h460v230H80zM80 150h160V50M240 210V150h180V50M420 210h120M240 210h300M330 210v70M170 150v130"/><path stroke-width="1" d="M240 150a45 45 0 0 1 45 45h-45M420 210a45 45 0 0 1 45 45h-45M80 150a40 40 0 0 1 40 40H80"/><rect x="100" y="65" width="95" height="60" rx="2"/><rect x="455" y="70" width="65" height="100" rx="3"/><path d="M270 70h125v100H270zM290 70v100M375 70v100"/></g><g fill="#999" font-family="Arial" font-size="9" text-anchor="middle"><text x="155" y="138">MEETING ROOM</text><text x="331" y="185">OPEN WORKSPACE</text><text x="485" y="190">PROJECT OFFICE</text><text x="118" y="235">LOBBY</text><text x="200" y="250">STORE</text><text x="285" y="250">SERVICE</text></g><g stroke="#3681bc" fill="none" stroke-width="1"><path d="M80 305h460M80 293v24M540 293v24M80 303l8 4M540 303l-8 4"/></g><text x="310" y="302" fill="#3681bc" font-size="10" text-anchor="middle">12,400 mm</text><g stroke="#c44e4e" fill="none" stroke-width="1.6"><ellipse cx="490" cy="125" rx="47" ry="70" stroke-dasharray="5 3"/><path d="M535 75l32-35"/></g><text x="560" y="33" fill="#c44e4e" font-size="9" text-anchor="middle">Review glazing</text><text x="80" y="335" fill="#999" font-family="Arial" font-size="9">GW / PROJECT 024</text><text x="540" y="335" text-anchor="end" fill="#999" font-family="Arial" font-size="9">GROUND FLOOR · 1:100</text></svg>; }
function WorkspaceCard() { return <div class="workspace-card"><div class="mock-title"><img src="icon.svg" alt=""/><span>Spanvision Infra · PDF</span><span class="mock-title-org">Spanvision Infra</span><i>—　□　×</i></div><div class="mock-tabs"><b>Home</b><span>Comment</span><span>Drawing</span><span>Organize</span><span>View</span></div><div class="mock-tools"><span>↖ <small>Select</small></span><span>▱ <small>Highlight</small></span><span>↗ <small>Measure</small></span><span>▤ <small>Text</small></span><span>⤢ <small>Fit page</small></span><span>↶ <small>Undo</small></span></div><div class="mock-document">Project 024 — Ground floor.pdf <span>×　＋</span></div><div class="mock-content"><aside><small>PAGES</small><div class="mini-page">01</div><span>1 / 3</span></aside><div class="mock-paper"><Floorplan/></div></div><div class="mock-status"><span>Ready</span><span>Scale 1:100</span><span>75%　−　＋</span></div></div>; }

function Preview() {
  const route=()=>location.hash.slice(1) || 'landing';
  const [screen,setScreen]=createSignal(route()),[scan,setScan]=createSignal(false),[scanState,setScanState]=createSignal('ready'),[scanProgress,setScanProgress]=createSignal(0),[filename,setFilename]=createSignal('Ground floor scan.pdf'),[error,setError]=createSignal(''),[success,setSuccess]=createSignal(''),[name,setName]=createSignal('Alex Morgan');
  let timer, upload, previousFocus;
  const stopScan=()=>{clearInterval(timer);timer=null;};
  const change=()=>{setScreen(route());setError('');setSuccess(''); window.scrollTo(0,0);};
  window.addEventListener('hashchange',change);
  onCleanup(()=>{window.removeEventListener('hashchange',change);stopScan();});
  function startScan() { stopScan();setScanProgress(0);setScanState('processing');timer=setInterval(()=>{setScanProgress(p=>Math.min(100,p+10));if(scanProgress()>=100){stopScan();setScanState('complete');}},160); }
  function closeScan(){stopScan();setScan(false);previousFocus?.focus();}
  function openScan(event){previousFocus=event.currentTarget;setScanState('ready');setScan(true);}
  function submit(event){event.preventDefault();const data=new FormData(event.currentTarget);const email=String(data.get('email')||'');const password=String(data.get('password')||'');setError(''); if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){setError('Enter a valid email address.');return;}if(password.length<8){setError('Use at least 8 characters for the preview password.');return;} if(screen()==='signup'&&!String(data.get('name')||'').trim()){setError('Enter your name.');return;}setName(String(data.get('name')||'Alex Morgan'));event.currentTarget.reset();location.hash='account';}
  const features=[['01','Mark up with confidence','Annotate, highlight and review. Keep every note exactly where it belongs.'],['02','Measure what matters','Calibrate drawings, measure distances and take off quantities to scale.'],['03','Keep work moving','Organize pages, compare revisions and make scanned documents searchable.']];
  return <>
    <header class="preview-header"><Mark/><nav aria-label="Main navigation"><a classList={{current:screen()==='landing'}} href="#landing">Overview</a><a classList={{current:screen()==='suggestions'}} href="#suggestions">Assistant</a><a classList={{current:screen()==='account'}} href="#account">Account</a></nav><a class="button button-light header-action" href="./">Open workspace <Arrow/></a></header>
    <main>
      <Show when={screen()==='landing'}><section class="hero"><div class="eyebrow"><span class="status-dot"/> BUILT FOR THE WORK IN FRONT OF YOU</div><h1>Clarity,<br/>on every page<span>.</span></h1><div class="hero-bottom"><p>Your documents, drawings and ideas.<br/>One focused workspace to move them forward.</p><div class="hero-actions"><a class="button button-light" href="./">Open workspace <Arrow/></a><button class="button button-outline" onClick={openScan}>Explore scan & OCR</button><small>No account needed. Your files stay yours.</small></div></div><WorkspaceCard/><div class="hero-caption"><span>PRECISION, WITHOUT THE DISTRACTIONS.</span><span>PDF EDITING / DRAWING / MEASUREMENT</span></div></section>
      <section class="features"><div class="section-intro"><span class="eyebrow">A BETTER WAY TO WORK</span><h2>From first review<br/>to final revision.</h2><p>The tools you need, in a familiar ribbon.<br/>Less friction between you and your next step.</p></div><div class="feature-grid"><For each={features}>{item=><article><span class="feature-number">/{item[0]}</span><h3>{item[1]}</h3><p>{item[2]}</p><a href="./" aria-label={'Open workspace to '+item[1].toLowerCase()}><Arrow/></a></article>}</For></div></section>
      <section class="photo-section"><div class="photo"><img loading="lazy" src="https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=85" alt="A bright, naturally colored business workspace with desks and greenery"/></div><div class="photo-copy"><span class="eyebrow">MADE FOR REAL PROJECTS</span><h2>Good work starts<br/>with a clear view.</h2><p>Review drawings with your team. Mark a revision. Turn a scanned sheet into a searchable document. Keep the focus on the work.</p><a class="button button-outline" href="./">Make your next mark <Arrow/></a></div></section>
      <section class="final-cta"><span class="eyebrow">SPANVISION INFRA / PDF WORKSPACE</span><h2>A little more clarity.<br/>A lot more possibility.</h2><a class="button button-light" href="./">Open workspace <Arrow/></a></section></Show>
      <Show when={screen()==='login'||screen()==='signup'}><section class="auth-layout"><div class="auth-story"><span class="eyebrow">YOUR WORK, IN FOCUS</span><h1>Make room<br/>for better work.</h1><p>Documents. Drawings. Done.</p><div class="auth-art"><Floorplan/></div><span class="auth-note">SPANVISION INFRA</span></div><div class="auth-form-wrap"><span class="preview-badge">ACCOUNT SCREEN PREVIEW</span><h2>{screen()==='signup'?'Create your workspace.':'Welcome back.'}</h2><p>{screen()==='signup'?'A clear start for your next project.':'Pick up where your work left off.'}</p><form novalidate onSubmit={submit}><Show when={screen()==='signup'}><label>Full name<input name="name" autocomplete="off" placeholder="Alex Morgan"/></label></Show><label>Email address<input name="email" type="email" autocomplete="off" placeholder="you@company.com"/></label><label>Password<input name="password" type="password" autocomplete="off" placeholder="At least 8 characters"/></label><Show when={error()}><p class="form-error" role="alert">{error()}</p></Show><button class="button button-light" type="submit">{screen()==='signup'?'Preview account':'Preview sign in'}<Arrow/></button></form><p class="auth-switch">{screen()==='signup'?'Already have an account?':'New to Spanvision Infra · PDF?'} <a href={screen()==='signup'?'#login':'#signup'}>{screen()==='signup'?'Sign in':'Create an account'}</a></p><div class="preview-disclosure">This is a local interface preview. No account is created and no credentials are transmitted or saved.</div><a class="quiet-link" href="./">Continue to the workspace without an account ↗</a></div></section></Show>
      <Show when={screen()==='account'}><section class="account-page"><span class="preview-badge">SAMPLE ACCOUNT · PREVIEW</span><div class="account-heading"><div><span class="eyebrow">YOUR WORKSPACE</span><h1>A clear view of you.</h1><p>Manage the details that make this workspace yours.</p></div><a href="./" class="button button-light">Open workspace <Arrow/></a></div><div class="account-grid"><aside class="account-nav"><button class="selected">Profile</button><a href="#suggestions">Assistant</a><a href="#login">Sign-in preview <Arrow/></a></aside><div class="account-card"><div class="profile-header"><span class="avatar">{name().split(' ').map(s=>s[0]).join('').slice(0,2)}</span><div><h2>{name()}</h2><p>Sample profile · Spanvision Infra</p></div></div><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);const value=String(data.get('name')||'').trim();if(!value){setError('Enter your name.');return;}setName(value);setError('');setSuccess('Profile updated in this preview.');}}><label>Display name<input name="name" value={name()}/></label><label>Organization<input value={BRAND.organization} readonly/></label><label>Interface theme<select><option>Spanvision Mono</option></select></label><Show when={error()}><p role="alert" class="form-error">{error()}</p></Show><Show when={success()}><p role="status" class="form-success">{success()}</p></Show><button class="button button-light">Save preview changes <Arrow/></button></form></div><div class="account-details"><article><span class="eyebrow">LOCAL BY DESIGN</span><h3>Your files. Your control.</h3><p>The editor works without an account. Cloud storage and live account services are not connected in this edition.</p></article><article><span class="eyebrow">APPEARANCE</span><div class="palette"><i/><i/><i/><i/></div><p>Spanvision Mono<br/>A quieter space for detailed work.</p></article></div></div></section></Show>
      <Show when={screen()==='suggestions'}><section class="suggestions-page"><span class="eyebrow">SPANVISION ASSISTANT</span><h1>A helpful<br/>second perspective.</h1><p>Bring context to your next step. Connect your own assistant in the editor.</p><div class="suggestion-grid"><For each={['Summarize this document','Translate selected text','Review a drawing','Create a measurement plan']}>{text=><a href="./" class="suggestion-card"><span>{text}</span><Arrow/></a>}</For></div><div class="suggestions-note">Suggestion preview · Open the editor to use your configured assistant or local MCP connection.</div><button class="button button-outline" onClick={openScan}>Explore scan & OCR <Arrow/></button></section></Show>
      <Show when={!['landing','login','signup','account','suggestions'].includes(screen())}><section class="suggestions-page"><h1>Page not found.</h1><a class="button button-light" href="#landing">Back to overview <Arrow/></a></section></Show>
    </main>
    <footer class="preview-footer"><Mark/><span>© 2026 Spanvision Infra</span><div><a href="#login">Sign in preview</a><a href="#signup">Sign up preview</a><a href="notices.md">Open-source notices</a></div></footer>
    <Show when={scan()}><Dialog title="Scan & make searchable" dialogClass="scan-preview-dialog" onClose={closeScan} footer={<><span class="preview-badge">NATIVE FEATURE PREVIEW</span><div class="scan-footer"><button class="button button-outline" onClick={()=>{stopScan();setScanState('ready');scanState()==='ready'&&closeScan();}}>Cancel</button><button class="button button-light" disabled={scanState()==='processing'} onClick={scanState()==='complete'?closeScan:startScan}>{scanState()==='complete'?'Done':'Preview OCR'}<Arrow/></button></div></>}><p class="scan-intro">Turn a scanned PDF into a document you can search.</p><input hidden ref={upload} type="file" accept="application/pdf,image/*" onChange={e=>{if(e.target.files?.[0])setFilename(e.target.files[0].name);}}/><button class="scan-upload" onClick={()=>upload?.click()} disabled={scanState()==='processing'}><span class="file-glyph">PDF</span><span><b>{filename()}</b><small>Choose a scanned PDF or image</small></span><span>＋</span></button><div class="scan-options"><label>Pages<select disabled={scanState()==='processing'}><option>All pages</option><option>Current page</option></select></label><label>Document language<select disabled={scanState()==='processing'}><option>Auto detect</option><option>English</option><option>Traditional Chinese</option><option>Chinese + English</option></select></label></div><Show when={scanState()==='processing'}><div class="scan-progress" role="status"><span>Recognizing text… <b>{scanProgress()}%</b></span><progress value={scanProgress()} max="100"/></div></Show><Show when={scanState()==='complete'}><p role="status" class="form-success">Preview complete. A searchable text layer would be added to your PDF.</p></Show><div class="preview-disclosure">This browser screen simulates OCR. Real recognition runs locally in the Windows app; your document is not uploaded.</div></Dialog></Show>
  </>;
}
render(()=><Preview/>,document.getElementById('preview-root'));
